<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/** @var $block \Ksolves\MultivendorMarketplace\Block\Order\Create\Invoice\KsItems */
?>
<?php $invoice_item = $block->getKsSalesInvoiceItem($block->getKsInvoice()->getKsInvoiceIncrementId(), $block->getKsOrderItemId());$ksShowStoreCurrency = $block->canKsShowOrderCurrencyValue();
 ?>
<?php $items = $block->getChildren($block->getKsBundleItem()); ?>
<?php $_count = count($items) ?>
<?php $_index = 0; ?>
<?php
/** @var \Magento\Catalog\Helper\Data $catalogHelper */
$catalogHelper = $block->getData('ksCatalogHelper');
$ksOrderHelper = $block->getData('ksOrderHelper');
?>
<?php if ($block->getKsBundleItem()->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php $_prevOptionId = '' ?>
<?php foreach ($items as $_item): $ksOrderItem = $block->getKsOrderItem($_item->getId()); $ksInvoiceItem = $block->getKsSalesInvoiceReqItem($block->getKsInvoice()->getEntityId(),$_item->getId());
    
    if(!$ksInvoiceItem->getEntityId()){
        continue;
    };

 ?>
    <?php if ($ksOrderItem->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
        <tr class="ks-bundle-item">
            <td class="col-product">
                <div class="option-label"><?= $block->escapeHtml($attributes['option_label']) ?></div>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="last">&nbsp;</td>
        </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr <?php if($ksOrderItem->getParentItem()):?> class="ks-bundle-item" <?php endif;?>>
        <?php if ($ksOrderItem->getParentItem()): ?>
        <td class="col-product">
            <div class="product-title"><?= $block->escapeHtml($_item->getName()) ?></div>
            <div class="product-sku-block">
                <span class="ks-order-item-sku"><?= $block->escapeHtml(__('SKU')) ?>:</span>
                <?= /* @noEscape */ implode('<br />', $catalogHelper->splitSku($_item->getSku())) ?>
            </div>
        <?php else: ?>
        <td class="col-product">
            <div class="option-value"><?= $block->getValueHtml($_item) ?></div>
        </td>
        <?php endif; ?>
        <td class="col-price">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <span><?= $block->formatValue($ksInvoiceItem->getKsBasePrice() + $ksOrderItem->getBaseWeeeTaxAppliedAmount()) ?></span>
                <br>
                <?php if($ksShowStoreCurrency):?>
                        <span><?= $block->formatToOrderCurrency($ksInvoiceItem->getKsPrice() + $ksOrderItem->getWeeeTaxAppliedAmount())?></span>
                <?php endif;?>
                <?php if ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ksOrderItem)) : ?>
                                        
                    <span>
                        <?php foreach ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ksOrderItem) as $ksTax) : ?>
                            <span class="nobr"><?= $block->escapeHtml($ksTax['title']) ?>:<?= $block->formatValue($ksTax['base_amount']) ?></span>
                            <br>
                            <?php if($ksShowStoreCurrency):?>
                                <span><?= $block->formatToOrderCurrency($ksTax['amount'])?></span>
                            <?php endif;?>                                                  
                        <?php endforeach; ?>
                    </span>
                <?php endif; ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-qty">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <?= (float)$ksInvoiceItem->getKsQty() * 1 ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-subtotal">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <span><?= $block->formatValue($ksInvoiceItem->getKsBasePrice()*$ksInvoiceItem->getKsQty() + ($ksOrderItem->getBaseWeeeTaxAppliedAmount() * $ksInvoiceItem->getKsQty())) ?></span>
                <br>
                <?php if($ksShowStoreCurrency):?>
                    <span><?= $block->formatToOrderCurrency($ksInvoiceItem->getKsPrice()*$ksInvoiceItem->getKsQty() + ($ksOrderItem->getWeeeTaxAppliedAmount() * $ksInvoiceItem->getKsQty()))?></span>
                <?php endif;?>
                <?php if ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ksOrderItem)) : ?>
                                        
                    <span>
                        <?php foreach ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ksOrderItem) as $ksTax) : ?>
                            <span class="nobr"><?= $block->escapeHtml($ksTax['title']) ?>:<?= $block->formatValue($ksTax['base_amount']) ?></span>
                            <br>
                            <?php if($ksShowStoreCurrency):?>
                                <span><?= $block->formatToOrderCurrency($ksTax['amount'])?></span>
                            <?php endif;?>                                                  
                        <?php endforeach; ?>
                    </span>
                <?php endif; ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-tax">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <span><?= $block->formatValue($ksInvoiceItem->getKsBaseTaxAmount()) ?></span>
                <br>
                <?php if($ksShowStoreCurrency):?>
                        <span><?= $block->formatToOrderCurrency($ksInvoiceItem->getKsTaxAmount())?></span>
                <?php endif;?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-discount">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <span><?= $block->formatValue($ksInvoiceItem->getKsBaseDiscountAmount()) ?></span>
                    <br>
                        <?php if($ksShowStoreCurrency):?>
                                <span><?= $block->formatToOrderCurrency($ksInvoiceItem->getKsDiscountAmount())?></span>
                        <?php endif;?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-total last">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <span><?= $block->formatValue($ksInvoiceItem->getKsBaseRowTotal()-$ksInvoiceItem->getKsBaseDiscountAmount() + ($ksOrderItem->getBaseWeeeTaxAppliedAmount() * $ksInvoiceItem->getKsQty()) + $ksOrderHelper->ksCalcItemBaseTaxAmt($ksOrderItem,$ksInvoiceItem->getKsQty())) ?></span>
                <br>
                <?php if($ksShowStoreCurrency):?>
                    <span><?= $block->formatToOrderCurrency($ksInvoiceItem->getKsRowTotal()-$ksInvoiceItem->getKsDiscountAmount() + ($ksOrderItem->getWeeeTaxAppliedAmount() * $ksInvoiceItem->getKsQty()) + $ksOrderHelper->ksCalcItemTaxAmt($ksOrderItem,$ksInvoiceItem->getKsQty()))?></span>
                <?php endif;?>
                <?php else: ?>
                 &nbsp;
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if ($_showlastRow): ?>
    <tr class="border">
        <td class="col-product">
            <?php if ($block->getOrderOptions($invoice_item)): ?>
                <dl class="item-options">
                <?php foreach ($block->getOrderOptions($invoice_item) as $option): ?>
                    <dt><?= $block->escapeHtml($option['label']) ?></dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?= $block->escapeHtml($option['value']) ?>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->truncateString($option['value'], 55, '', $_remainder)) ?>
                        <?php if ($_remainder):?>
                            ... <span id="<?= $block->escapeHtmlAttr($_id = 'id' . uniqid())
                            ?>"><?= $block->escapeHtml($_remainder) ?></span>
                            <?php $escapedId = /* @noEscape */ $block->escapeJs($_id);
                            $scriptString = <<<script
                                require(['prototype'], function(){
                                    $('{$escapedId}').hide();
                                    $('{$escapedId}').up().observe('mouseover', function(){\$('{$escapedId}').show();});
                                    $('{$escapedId}').up().observe('mouseout',  function(){\$('{$escapedId}').hide();});
                                });
script;
                            ?>
                            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?= $block->escapeHtml($block->getItem()->getDescription()) ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>
