<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/** @var \Ksolves\Multivendor\Block\FavouriteSeller\KsShowData $block  */
?>

<div class="ks-mail-follower">
    <button type="button" class="ks-multiplesendmail ks-action-btn ks-primary" disabled="true"><?= $block->escapeHtml(__('Email Followers')) ?></button>
</div>