<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div class="loading-mask">
    <div class="loader">
        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
             alt="<?= $escaper->escapeHtmlAttr(__('Loading...')) ?>"
             style="position: absolute;">
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_LoginAsCustomerFrontendUi/js/login": {
            "redirectUrl": "<?= /* @noEscape */ $block->getUrl('multivendor/sellerprofile/homepage') ?>"
        }
    }
}
</script>
