<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

$ksAttributeSetId = ((int) $this->getRequest()->getParam('set')) ? (int) $this->getRequest()->getParam('set') : $block->getKsAttributeValue();
?>

<fieldset class="ks-form-field ks-attribute-set">
     <div class="ks-control-grouped">
         <div class="ks-form-field">
             <div class="ks-form-field-label">
                 <label>
                    <span><?= $block->escapeHtml(__("Attribute Set"));?></span>
                 </label>
             </div>
            <div class="ks-field-control ks-control-grouped">
                <div class="ks-action-multiselect-wrap">
                    <div data-bind="scope: 'ksAttributeSet'">
                    <!-- ko template: getTemplate() -->
                    <!-- /ko -->
                    </div>
                    <script type="text/x-magento-init">
                    {
                        "*": {
                            "Magento_Ui/js/core/app": {
                                "components": {
                                    "ksAttributeSet": {
                                        "component": "Ksolves_MultivendorMarketplace/js/product/attributeset/ks-ui-select",
                                        "template" : "Ksolves_MultivendorMarketplace/product/attributeset/ui-select",
                                        "filterOptions": true,
                                        "levelsVisibility": "1",
                                        "multiple": false,
                                        "showCheckbox": false,
                                        "options": <?= $block->getKsAttributeSetOption()?>,
                                        "value": <?= $ksAttributeSetId?>
                                    }
                                }
                            }
                        }
                    }
                    </script>
                </div>
            </div>
         </div>
     </div>
</fieldset>
    