<!--
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
-->
<div class="w-fit-content ml-auto float-right">
	<a href="<?= $block->getUrl('multivendor/productattribute_set/new') ?>">
		<button type="button" title="Add Attribute Set" class="ks-action-btn ks-primary">
			<span><?= $block->escapeHtml(__("Add Attribute Set")) ?></span>
		</button>
	</a>
</div>