<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright(c) Ksolves India Limited(https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

// Created Helper Object
$ksHelper = $this->helper('Ksolves\MultivendorMarketplace\Helper\KsDataHelper');
// Get seller registration allowed or not
$ksSellerRegistration = $ksHelper->getKsConfigValue('ks_marketplace_login_and_registration/ks_marketplace_login_and_registration_settings/ks_allow_seller_registration', $ksHelper->getKsCurrentStoreView());
?>

<div class="ks-account-page ks-page-content">
    <header class="ks-account-header">
        <div class="ks-section-container">
            <div class="ks-account-logo">
                <a href="<?= $block->getBaseUrl()?>"><img src="<?= $this->getViewFileUrl('Ksolves_MultivendorMarketplace::images/seller-logo.png') ?>"/></a>
            </div>
            <?php if($ksSellerRegistration): ?>
                <div class="ks-header-title">
                    <span>New Seller?</span><a href="<?= $block->getUrl('customer/account/create') ?>">Create An Account</a>
                </div>
            <?php endif; ?>
        </div>
    </header>
    <div class="ks_container">
        <div class="ks_row">
            <form class="ks-account-login-form ks-account-form form-login login-container ks-account-forgot-form"
            action="<?= $block->getBaseUrl().'multivendor/forgotpassword/forgotpasswordpost/'?>"
            method="post" id="login-form" data-mage-init='{"validation":{}}'>
                <h1><?= $block->escapeHtml(__('Forgot Your Password?')) ?></h1>
                <div class="fieldset login ks-mb-0">
                    <div class="field ks-form-note"></div>
                    <div class="field ks-form-note ks-form-note-message"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
                    <div class="field email required">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input type="email" name="email" alt="email" placeholder="Email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <div class="ks-submit-forgot-button">
                        <button type="submit" class="ks-frontend-btn ks-account-btn ks-frontend-medium-btn">
                            <span><?= /* @escapeNotVerified */$block->escapeHtml(__('Reset My Password')) ?></span>
                        </button>               
                    </div>   
                </div>
            </form>
        </div>
    </div>
</div>
