<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright(c) Ksolves India Limited(https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
?>

<div class="ks-account-page ks-page-content">
    <header class="ks-account-header">
        <div class="ks-section-container">
            <div class="ks-account-logo">
                <a href="<?= $block->getBaseUrl()?>"><img src="<?= $this->getViewFileUrl('Ksolves_MultivendorMarketplace::images/seller-logo.png') ?>"/></a>
            </div>
        </div>
    </header>
    <div class="ks_container">
        <div class="ks_row">
            <form class="ks-account-login-form ks-account-form form-login login-container ks-account-reset-form"
            action="<?= $block->escapeUrl($block->getUrl('multivendor/createpassword/resetpasswordpost/', ['_query' => ['token' => $block->getResetPasswordLinkToken()]])) ?>"
            method="post" id="login-form" data-mage-init='{"validation":{}}'>
                <h1><?= $block->escapeHtml(__('Set a New Password')) ?></h1>
                <div class="fieldset login ks-mb-0">
                    <div class="field ks-form-note"></div>
                    <div class="field password required"  data-mage-init='{"passwordStrengthIndicator": {
                            "passwordStrengthMeterSelector":"[data-role=strength-meter]",
                            "passwordStrengthMeterLabelSelector":"[data-role=strength-meter-label]"
                            }}'>
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="password" id="password"
                            data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                            data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>" 
                            data-validate="{required:true,'validate-customer-password':true}"
                            placeholder="Password"
                            autocomplete="off">
                            <div id="password-strength-meter-container" data-role="strength-meter" aria-live="polite">
                                <div id="password-strength-meter" class="password-strength-meter">
                                    <span id="password-strength-meter-label" data-role="strength-meter-label">
                                    <?= $block->escapeHtml(__('No Password')) ?>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field password required">
                        <label for="pass" class="label"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
                        <div class="control">
                            <input type="password" class="input-text" name="password_confirmation" placeholder="Confirm Password" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off">
                        </div>
                    </div>
                    <div class="ks-submit-reset-button">
                        <button type="submit" class="ks-frontend-btn ks-account-btn ks-frontend-medium-btn">
                            <span><?= /* @escapeNotVerified */$block->escapeHtml(__('Set a New Password')) ?></span>
                        </button>               
                    </div>   
                </div>
            </form>
        </div>
    </div>
</div>
