<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

?>
<?php /** @var $block \Ksolves\MultivendorMarketplace\Block\Product\Form\Tabs\Options\Type\KsDate */ ?>
<script id="ks-custom-option-date-type-template" type="text/x-magento-template">
    <div id="product_option_<%- data.option_id %>_type_<%- data.group %>" class="fieldset ks-product-table-parent">
        <table class="data-table">
            <thead>
            <tr class="headings">
                <?php if ($block->getCanReadPrice() !== false): ?>
                <th class="pb-0"><?= $block->escapeHtml(__('Price')) ?></th>
                <th class="pb-0"><?= $block->escapeHtml(__('Price Type')) ?></th>
                <?php endif; ?>
                <th class="pb-0"><?= $block->escapeHtml(__('SKU')) ?></th>
            </tr>
            </thead>
            <tr>
                <?php if ($block->getCanReadPrice() !== false): ?>
                <td class="opt-price">
                    <div class="ks-dollor-sign">
                        <span>
                            <% if(data.price_type=="percent") {%>%<% } %>
                            <% if(!data.price_type || data.price_type=="fixed") {%>
                            <?= $block->getKsCurrentCurrency();?><% } %>
                        </span>
                        <input id="product_option_<%- data.option_id %>_price"
                               name="product[options][<%- data.option_id %>][price]"
                               class="input-text validate-number product-option-price"
                               type="text" value="<%- data.price %>" data-store-label="<%- data.price %>"
                               data-price-sysmbol="<?= $block->getKsCurrentCurrency();?>"
                            <?php if ($block->getCanEditPrice() === false): ?>
                               disabled="disabled"
                            <?php endif; ?>>
                    </div>
                </td>
                <td class="opt-price-type">
                    <?= $block->getPriceTypeSelectHtml('data-attr="price-type"') ?>
                </td>
                <?php else: ?>
                    <input id="product_option_<%- data.option_id %>_price" name="product[options][<%- data.option_id %>][price]" type="hidden">
                    <input id="product_option_<%- data.option_id %>_price_type" name="product[options][<%- data.option_id %>][price_type]" type="hidden">
                <?php endif; ?>
                <td>
                    <input name="product[options][<%- data.option_id %>][sku]" class="input-text type-sku" value="<%- data.sku %>" type="text">
                </td>
            </tr>
        </table>
    </div>
</script>
