<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
?>
<?php /** @var $block \Ksolves\MultivendorMarketplace\Block\Product\Form\Tabs\Options\Type\KsFile */ ?>
<script id="ks-custom-option-file-type-template" type="text/x-magento-template">
    <div id="product_option_<%- data.option_id %>_type_<%- data.group %>" class="fieldset ks-product-table-parent">
        <table class="data-table">
            <thead>
            <tr>
                <?php if ($block->getCanReadPrice() !== false): ?>
                    <th class="pb-0"><?= $block->escapeHtml(__('Price')) ?></th>
                    <th class="pb-0"><?= $block->escapeHtml(__('Price Type')) ?></th>
                <?php endif; ?>
                <th class="pb-0"><?= $block->escapeHtml(__('SKU')) ?></th>
                <th class="pb-0 ks-required"><?= $block->escapeHtml(__('Compatible File Extensions')) ?></th>
                <th class="pb-0"><?= $block->escapeHtml(__('Maximum Image Size')) ?></th>
                <th class="pb-0"></th>
            </tr>
            </thead>
            <tr>
                <?php if ($block->getCanReadPrice() !== false): ?>
                    <td class="opt-price">
                        <div class="ks-dollor-sign">
                            <span>
                                <% if(data.price_type=="percent") {%>%<% } %>
                                <% if(!data.price_type || data.price_type=="fixed") {%>
                                <?= $block->getKsCurrentCurrency();?><% } %>
                            </span>
                            <input name="product[options][<%- data.option_id %>][price]" data-store-label="<%- data.price %>"
                                   class="input-text validate-zero-or-greater product-option-price" type="text" value="<%- data.price %>"
                                   data-price-sysmbol="<?= $block->getKsCurrentCurrency();?>"
                                <?php if ($block->getCanEditPrice() === false): ?>
                                    disabled="disabled"
                                <?php endif; ?>>
                        </div>
                    </td>
                    <td class="opt-price-type"><?= $block->getPriceTypeSelectHtml('data-attr="price-type"') ?></td>
                <?php else: ?>
                    <input name="product[options][<%- data.option_id %>][price]" type="hidden">
                    <input id="product_option_<%- data.option_id %>_price_type" name="product[options][<%- data.option_id %>][price_type]" type="hidden">
                <?php endif; ?>
                <td>
                    <input name="product[options][<%- data.option_id %>][sku]" class="input-text" type="text" value="<%- data.sku %>">
                </td>
                <td>
                    <input name="product[options][<%- data.option_id %>][file_extension]" class="input-text required-entry" type="text" value="<%- data.file_extension %>">
                    <div class="note ks-field-note"><?= $block->escapeHtml(__('Enter separated extensions, like: png, jpg, gif.')) ?></div>
                </td>
                <td class="ks-field-value-note">
                    <input class="input-text" type="text" name="product[options][<%- data.option_id %>][image_size_x]" value="<%- data.image_size_x %>">
                    <label><span><?= $block->escapeHtmlAttr("Px") ?></span></label>
                    <div class="note ks-field-note"><?= $block->escapeHtml(__('Please leave blank if it is not an image.')) ?></div>
                </td>
                <td class="ks-field-value-note">
                    <input class="input-text" type="text" name="product[options][<%- data.option_id %>][image_size_y]" value="<%- data.image_size_y %>"/>
                    <label><span><?= $block->escapeHtmlAttr("Px") ?></span></label>
                </td>
            </tr>
        </table>
    </div>
</script>
