<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
?>
<?php

/**
 * @var $block \Ksolves\MultivendorMarketplace\Block\Product\Form\Tabs\Downloadable\KsLinks
 */
?>
<?php $ksProduct = $block->getKsProduct()?>

<div class="fieldset downloadable-form mb-0" data-ui-id="downloadable-links">
    <div class="ks-heading-title ml-5"><span><?= $block->escapeHtml(__('Links')) ?></span></div>
    <!--p class="note"><//?= $block->escapeHtml(__('Add links to your product files here.')) ?></p-->
    <div class="ks-fieldset-wrapper-content">
        <fieldset class="ks-form-fieldset pt-3">
            <fieldset class="ks-form-field">
                <div class="ks-control-grouped">
                    <div class="ks-form-field" <?= $block->escapeHtml(!$block->ksIsSingleStoreMode() ? ' data-config-scope="' . __('[STORE VIEW]') . '"' : '') ?>>
                        <div class="ks-form-field-label">
                            <label for="downloadable_links_title"><span data-config-scope="[STORE VIEW]"><?= $block->escapeHtml(__('Title')) ?></span></label>
                        </div>
                        <div class="ks-field-control">
                            <input type="text" class="control-text" id="downloadable_links_title" name="product[links_title]" value="<?= $block->escapeHtml($block->getKsLinksTitle()) ?>" <?= ($ksProduct->getStoreId() && $block->getKsUsedDefault()) ? 'disabled="disabled"' : '' ?>>
                            <?php if ($ksProduct->getStoreId()): ?>
                                <div class="field field-option">
                                    <input id="link_title_default" class="control-checkbox" type="checkbox" name="use_default[]" value="links_title" onclick="toggleValueElements(this, this.parentNode.parentNode)" <?= $block->getKsUsedDefault() ? 'checked="checked"' : '' ?> />
                                    <label class="field-label" for="link_title_default"><span><?= $block->escapeHtml(__('Use Default Value')) ?></span></label>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </fieldset>

            <fieldset class="ks-form-field ks-link-disable">
                <div class="ks-control-grouped">
                    <div class="field ks-form-field" <?= $block->escapeHtml(!$block->ksIsSingleStoreMode() ? ' data-config-scope="' . __('[GLOBAL]') . '"' : '') ?>>
                        <div class="ks-form-field-label">
                            <label for="downloadable_links_title"><span data-config-scope="[GLOBAL]"></span></label>
                        </div>
                        <div class="field-control ks-field-control">
                            <input type="checkbox" name="product[links_purchased_separately]" value="1" class="control-checkbox" id="link-switcher1" 
                            <?php if ($block->ksIsProductLinksCanBePurchasedSeparately()): ?> 
                                checked="checked"
                            <?php endif; ?> />
                            <label class="field-label" for="downloadable_link_purchase_type"><span><?= $block->escapeHtml(__('Links can be purchased separately')) ?></span></label>
                        </div>
                    </div>
                </div>
            </fieldset>

            <fieldset class="field field-wide ks-form-field mb-5">
                <div class="field-control">
                    <div class="control-table-wrapper ks-control-table-wrapper ks-product-table-parent">
                        <table class="control-table table ks-product-table">
                            <thead>
                                <tr>
                                    <th class="col-sort"><span><!--?= $block->escapeHtml(__('Sort Order')) ?--></span></th>
                                    <th class="col-title _required"><span><?= $block->escapeHtml(__('Title')) ?></span></th>
                                    <?php if ($block->getCanReadPrice() !== false): ?>
                                        <th class="col-price"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
                                    <?php endif; ?>
                                    <th class="col-file"><span><?= $block->escapeHtml(__('File')) ?></span></th>
                                    <th class="col-sample"><span><?= $block->escapeHtml(__('Sample')) ?></span></th>
                                    <th class="col-share"><span><?= $block->escapeHtml(__('Shareable')) ?></span></th>
                                    <th class="col-limit"><span><?= $block->escapeHtml(__('Max. Downloads')) ?></span></th>
                                    <th class="col-actions">&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody id="link_items_body">
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td class="col-actions-add ks-col-actions-add" colspan="8"><button data-ui-id="widget-button-7" data-action="add-link" class="primary scalable action-add" type="button" title="Add New Link" id="add_link_item">
                                            <span><?= $block->escapeHtml(__('Add Link')) ?></span>
                                        </button>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </fieldset>

            <div class="field-note">
                <span><?= $block->escapeHtml(__('Alphanumeric, dash and underscore characters are recommended for filenames. Improper characters are replaced with \'_\'.')) ?></span>
            </div>
        </fieldset>
    </div>
</div>

<script>
require([
    'jquery',
    'uiRegistry',
    'mage/template',
    'jquery/file-uploader',
    'mage/mage',
    'prototype',
    'mage/translate'
], function(jQuery, registry, mageTemplate){
    registry.get('downloadable', function (Downloadable) {
        var linkTemplate = '<tr>'+
            '<td data-role="draggable-handle"><input data-container="link-order" type="hidden" ' +
            'name="downloadable[link][<%- ' +
            'data.id' +
            ' %>][sort_order]" ' +
            'value="<%- data.sort_order %>" class="input-text control-text sort" />' +
            '<span class="draggable-handle ks-draggable-handle" title="<?= $block->escapeJs($block->escapeHtml(__('Sort Variations'))) ?>"></span>' +
            '</td>'+
            '<td class="col-title ks-product-form-style">'+
                '<input type="hidden" class="__delete__" name="downloadable[link][<%- data.id %>][is_delete]" value="" />'+
                '<input type="hidden" name="downloadable[link][<%- data.id %>][record_id]" value="<%- data.id %>" />'+
                '<% if (data.link_id) { %> <input type="hidden" name="downloadable[link][<%- data.id %>][link_id]" value="<%- data.link_id %>" /> <% } %>'+
                '<input type="text" class="required-entry input-text control-text" name="downloadable[link][<%- data.id %>][title]" value="<%- data.title %>" />'+
                <?php if ($ksProduct->getStoreId()): ?>
                    '<div class="field field-option">'+
                    '<input type="checkbox" id="downloadable_link_<%- data.id %>_title" name="downloadable[link][<%- data.id %>][use_default_title]" value="1" class="control-checkbox" />'+
                    '<label for="downloadable_link_<%- data.id %>_title" class="field-label"><span><?= $block->escapeJs($block->escapeHtml(__('Use Default Value'))) ?></span></label>'+
                    '</div>' +
                <?php endif; ?>

                <?php if ($block->getCanReadPrice() === false): ?>
                    '<input type="hidden" id="downloadable_link_<%- data.id %>_price_value" class="link-prices" name="downloadable[link][<%- data.id %>][price]" value="0" />' +
                    <?php if ($ksProduct->getStoreId() && $block->getKsIsPriceWebsiteScope()): ?>
                    '<input type="hidden"  name="downloadable[link][<%- data.id %>][use_default_price]" value="1" />' +
                    <?php endif; ?>
                <?php endif; ?>
            '</td>'+
            <?php if ($block->getCanReadPrice() !== false): ?>
                '<td class="col-price ks-product-form-style">'+
                    '<div class="control-addon ks-dollor-sign">' +
                        '<span><?= $block->escapeHtml($block->getKsBaseCurrencyCode($ksProduct->getStoreId())) ?></span>' +
                        '<input type="text" id="downloadable_link_<%- data.id %>_price_value" class="input-text control-text validate-number link-prices<?php if ($block->getCanEditPrice() === false): ?> disabled<?php endif; ?>" name="downloadable[link][<%- data.id %>][price]" value="<%- data.price %>"<?php if ($block->getCanEditPrice() === false): ?> disabled="disabled"<?php endif; ?> /> ' +
                    '</div>' +
                    <?php if ($ksProduct->getStoreId() && $block->getKsIsPriceWebsiteScope()): ?>
                        '<div class="field field-option">'+
                            '<input type="checkbox" id="downloadable_link_<%- data.id %>_price" name="downloadable[link][<%- data.id %>][use_default_price]" value="1"<?php if ($block->getCanEditPrice() === false): ?> disabled="disabled"<?php endif; ?> class="control-checkbox" />'+
                            '<label for="downloadable_link_<%- data.id %>_price" class="field-label"><span><?= $block->escapeJs($block->escapeHtml(__('Use Default Value'))) ?></span></label>' +
                        '</div>' +
                    <?php endif; ?>
                '</td>' +
            <?php endif; ?>
            '<td class="col-file ks-product-form-style ks-control-fields">'+
                '<div class="ks-field">'+
                    '<div class="field field-option ks-field-option ks-control-fields">'+
                        '<div class="ks-field">'+
                            '<div class=""><select class="control-select" name="downloadable[link][<%- data.id %>][type]" id="downloadable_link_<%- data.id %>_type" onchange="ksLinkFileUrlFieldShowHide(this.value, <%- data.id %>)" />' +
                                '<option value="file" id="downloadable_link_<%- data.id %>_file_type" <%- data.file_selected %> ><?= $block->escapeJs($block->escapeHtml(__('Upload File'))) ?></option>'+
                                '<option value="url" id="downloadable_link_<%- data.id %>_url_type" <%- data.url_selected %> ><?= $block->escapeJs($block->escapeHtml(__('URL'))) ?></option>'+
                            '</select></div>' +
                        '</div>'+
                        '<input type="hidden" class="validate-downloadable-file" id="downloadable_link_<%- data.id %>_file_save" name="downloadable[link][<%- data.id %>][file]" value="<%- data.file_save %>" />'+
                        '<div id="downloadable_link_<%- data.id %>_file" class="field-uploader mt-4" <% if (data.link_type == "url") { %> style="display:none" <% } %> >'+
                            '<div id="downloadable_link_<%- data.id %>_file-old" class="file-row-info"></div>'+
                            '<div id="downloadable_link_<%- data.id %>_file-new" class="file-row-info new-file"></div>'+
                            '<div class="fileinput-button form-buttons ks-file-upload-area">'+
                                '<label class="ks-secondry ks-secondry-child ks-action-btn ks-file-uploader-button" for=""><?= $block->escapeJs($block->escapeHtml(__('Browse Files...'))) ?></label>' +
                                '<input id="downloadable_link_<%- data.id %>_file" type="file" name="<?= $block->escapeJs($block->escapeHtmlAttr($block->getKsFileFieldName('links'), '"')) ?>" class="<% if (data.link_type == "file" && !data.file_save) { %> required-entry <% } %>">' +
                                '<script>' +
                                    'linksUploader("#downloadable_link_<%- data.id %>_file", "<?=  $block->escapeUrl($block->getUrl('multivendor/product_downloadable_file/ksupload', ['type' => 'links', '_secure'=>$this->getRequest()->isSecure()])) ?>"); ' +
                                '</scr'+'ipt>'+
                            '</div>'+
                        '</div>'+
                        '<input type="text" class="validate-downloadable-url mt-4 validate-url control-text <% if (data.link_type == "url") { %> required-entry <% } %>" name="downloadable[link][<%- data.id %>][link_url]" id="downloadable_link_<%- data.id %>_url" value="<%- data.link_url %>" <% if (data.link_type == "file") { %> style="display:none" <% } %> placeholder="<?= $block->escapeJs($block->escapeHtmlAttr(__('URL'))) ?>" />'+
                    '</div>'+
                '</div>'+
                '<div>'+
                    '<span id="downloadable_link_<%- data.id %>_link_container"></span>'+
                '</div>'+
            '</td>'+
            '<td class="col-sample ks-product-form-style ks-control-fields">'+
                '<div class="ks-field">'+
                    '<div class="field field-option ks-field-option ks-control-fields">'+
                        '<div class="ks-field">'+
                            '<div class=""><select class="control-select" name="downloadable[link][<%- data.id %>][sample][type]" id="downloadable_link_<%- data.id %>_sample_type" onchange="ksLinkSampleFileUrlFieldShowHide(this.value, <%- data.id %>)" />' +
                                '<option value="file" id="downloadable_link_<%- data.id %>_sample_file_type" <%- data.sample_file_selected %> ><?= $block->escapeJs($block->escapeHtml(__('Upload File'))) ?></option>'+
                                '<option value="url" id="downloadable_link_<%- data.id %>_sample_url_type" <%- data.sample_url_selected %> ><?= $block->escapeJs($block->escapeHtml(__('URL'))) ?></option>'+
                            '</select></div>' +
                        '</div>'+
                        '<input type="hidden" id="downloadable_link_<%- data.id %>_sample_file_save" name="downloadable[link][<%- data.id %>][sample][file]" value="<%- data.sample_file_save %>" class="validate-downloadable-file" />'+
                        '<div id="downloadable_link_<%- data.id %>_sample_file" class="field-uploader mt-4" <% if (data.sample_type == "url") { %> style="display:none" <% } %> >'+
                            '<div id="downloadable_link_<%- data.id %>_sample_file-old" class="file-row-info"></div>'+
                            '<div id="downloadable_link_<%- data.id %>_sample_file-new" class="file-row-info new-file"></div>'+
                            '<div class="fileinput-button form-buttons ks-file-upload-area">'+
                            '<label class="ks-secondry ks-secondry-child ks-action-btn ks-file-uploader-button" for=""><?= $block->escapeJs($block->escapeHtml(__('Browse Files...'))) ?></label>' +
                            '<input id="downloadable_link_<%- data.id %>_sample_file" type="file" name="link_samples">' +
                            '<script>'+
                                'linksUploader("#downloadable_link_<%- data.id %>_sample_file", "<?=  $block->escapeUrl($block->getUrl('multivendor/product_downloadable_file/ksupload', ['type' => 'link_samples', '_secure'=>$this->getRequest()->isSecure()])) ?>"); ' +
                            '</scr'+'ipt>'+
                            '</div>'+
                        '</div>'+
                        '<input type="text" class="validate-downloadable-url mt-4 validate-url control-text" name="downloadable[link][<%- data.id %>][sample][url]" value="<%- data.sample_url %>" id="downloadable_link_<%- data.id %>_sample_url" <% if (data.sample_type!="" && data.sample_type != "url") { %> style="display:none" <% } %> placeholder="<?= $block->escapeJs($block->escapeHtmlAttr(__('URL'))) ?>" />'+
                    '</div>'+
                '</div>'+
                '<div>'+
                    '<span id="downloadable_link_<%- data.id %>_sample_container"></span>'+
                '</div>'+
            '</td>'+
            '<td class="col-share ks-product-form-style">'+
                '<select id="downloadable_link _<%- data.id %>_shareable" class="control-select" name="downloadable[link][<%- data.id %>][is_shareable]">'+
                    '<option value="1"><?= $block->escapeJs($block->escapeHtml(__('Yes'))) ?></option>'+
                    '<option value="0"><?= $block->escapeJs($block->escapeHtml(__('No'))) ?></option>'+
                    '<option value="2" selected="selected"><?= $block->escapeJs($block->escapeHtml(__('Use config'))) ?></option>'+
                '</select>'+
            '</td>'+
            '<td class="col-limit ks-product-form-style">' +
                '<input type="text" id="downloadable_link_<%- data.id %>_downloads" name="downloadable[link][<%- data.id %>][number_of_downloads]" class="input-text validate-zero-or-greater control-text downloads" value="<%- data.number_of_downloads %>" />'+
                '<div class="field field-option mt-4">' +
                    '<input type="checkbox" class="control-checkbox" id="downloadable_link_<%- data.id %>_is_unlimited" name="downloadable[link][<%- data.id %>][is_unlimited]" value="1" <%- data.is_unlimited %> />' +
                    '<label for="downloadable_link_<%- data.id %>_is_unlimited" class="field-label"><span><?= $block->escapeJs($block->escapeHtml(__('Unlimited'))) ?></span></label>' +
                '</div>' +
            '</td>'+
            '<td class="col-action ks-col-delete">'+
                '<button id="downloadable_link_<%- data.id %>_delete_button" type="button" class="action-delete" title="<?= $block->escapeJs($block->escapeHtmlAttr(__('Delete'))) ?>"><span><?= $block->escapeJs($block->escapeHtml(__('Delete'))) ?></span></button>'+
            '</td>'+
        '</tr>';

        var linkItems = {
            tbody : $('link_items_body'),
            templateText : linkTemplate,
            itemCount : 0,
            add : function(data) {
                alertAlreadyDisplayed = false;
                this.template = mageTemplate(this.templateText);

                if(!data.link_id){
                    data = {};
                    data.link_id  = 0;
                    data.link_type = 'file';
                    data.sample_type = 'none';
                    data.number_of_downloads = '<?= $block->escapeJs($block->getKsConfigMaxDownloads()) ?>';
                    data.sort_order = this.itemCount + 1;
                }

                data.id = this.itemCount;

                if (data.link_type == 'url') {
                    data.url_selected = ' selected="selected"';
                } else if (data.link_type == 'file') {
                    data.file_selected = ' selected="selected"';
                }
                if (data.sample_type == 'url') {
                    data.sample_url_selected = ' selected="selected"';
                } else if (data.sample_type == 'file') {
                    data.sample_file_selected = ' selected="selected"';
                }

                var rowElement = Element.insert(this.tbody, {
                    'bottom': this.template({data: data})
                });

                scopeTitle = $('downloadable_link_'+data.id+'_title');
                if (scopeTitle) {
                    Event.observe(scopeTitle, 'click', function(event){ 
                        scopeElm = $(Event.findElement(event, 'input')); 
                        titleField = scopeElm.up(1).down('input[type="text"]');
                        if (scopeElm.checked == true) {
                            titleField.disabled = true;
                        } else {
                            titleField.disabled = false;
                        }
                    });
                } 
                
                if (!data.store_title && scopeTitle && data.title) {
                    scopeTitle.up(1).down('input[type="text"]').disabled = true;
                    scopeTitle.checked = true;
                }
                
                scopePrice = $('downloadable_link_'+data.id+'_price');
                scopePriceField = $('downloadable_link_'+data.id+'_price_value');
                if (scopePrice) {
                    Event.observe(scopePrice, 'click', function(event){ 
                        scopeElm = $(Event.findElement(event, 'input'));
                        priceField = scopeElm.up(1).down('input[type="text"]');
                        ksPurchaseLinkElm = $('link-switcher1');
                        if(ksPurchaseLinkElm.checked == true) 
                        {
                            if (scopeElm.checked == true) {
                                priceField.disabled = true;
                                scopePrice.up(1).down('.ks-dollor-sign').addClassName("disabled");
                            } else {
                                priceField.disabled = false;
                                scopePrice.up(1).down('.ks-dollor-sign').removeClassName("disabled");
                            }
                        }
                    });
                }
                if (!data.website_price && scopePrice && data.price) {
                    scopePrice.up(1).down('input[type="text"]').disabled = true;
                    scopePrice.checked = true;
                    scopePrice.up(1).down('.ks-dollor-sign').addClassName("disabled");
                }
                downloadsElm = $('downloadable_link_'+data.id+'_downloads');
                isUnlimitedElm = $('downloadable_link_'+data.id+'_is_unlimited');
                if (data.is_unlimited) {
                    downloadsElm.disabled = true;
                }
                Event.observe(isUnlimitedElm, 'click', function(event){
                    elm = Event.element(event);
                    elm.up('td').down('input[type="text"].downloads').disabled = elm.checked;
                });

                if (data.is_shareable) {
                    options = $('downloadable_link _'+data.id+'_shareable').options;
                    for (var i=0; i < options.length; i++) {
                        if (options[i].value == data.is_shareable) {
                            options[i].selected = true;
                        }
                    }
                }

                sampleUrl = $('downloadable_link_'+data.id+'_sample_url_type');
                linkUrl = $('downloadable_link_'+data.id+'_url_type');

                if (!data.file_save) {
                    data.file_save = [];
                }
                if (!data.sample_file_save) {
                    data.sample_file_save = [];
                }

                // link sample file
                new Downloadable.FileUploader(
                    'linkssample',
                    'linkssample_'+data.id,
                    sampleUrl.up('td'),
                    'downloadable[link]['+data.id+'][sample]',
                    data.sample_file_save,
                    'downloadable_link_'+data.id+'_sample_file',
                    <?= /* @noEscape */ $block->getKsConfigJson('link_samples') ?>
                );
                // link file
                new Downloadable.FileUploader(
                    'links',
                    'links_'+data.id,
                    linkUrl.up('td'),
                    'downloadable[link]['+data.id+']',
                    data.file_save,
                    'downloadable_link_'+data.id+'_file',
                    <?= /* @noEscape */ $block->getKsConfigJson() ?>
                );

                linkFile = $('downloadable_link_'+data.id+'_file_type');
                linkFile.advaiceContainer = 'downloadable_link_'+data.id+'_link_container';
                linkUrl.advaiceContainer = 'downloadable_link_'+data.id+'_link_container';
                $('downloadable_link_'+data.id+'_file_save').advaiceContainer = 'downloadable_link_'+data.id+'_link_container';

                sampleFile = $('downloadable_link_'+data.id+'_sample_file_type');

                this.itemCount++;
                this.togglePriceFields();
                this.bindRemoveButtons();
            },
            sorting: function () {
                var list = jQuery(this.tbody);
                list.sortable({
                    axis: 'y',
                    handle: '[data-role=draggable-handle]',
                    items: 'tr',
                    update: function (event, data) {
                        list.find('[data-container=link-order]').each(function (i, el) {
                            jQuery(el).val(i + 1);
                        });
                    },
                    tolerance: 'pointer'
                });
            },
            remove : function(event){
                var element = $(Event.findElement(event, 'tr'));
                alertAlreadyDisplayed = false;
                if(element){
                    element.down('input[type="hidden"].__delete__').value = '1';
                    Element.select(element, 'div.flex').each(function(elm){
                        elm.remove();
                    });
                    element.addClassName('no-display');
                    element.addClassName('ignore-validate');
                    element.hide();
                }
            },
            bindRemoveButtons : function(){
                var buttons = $$('tbody#link_items_body .action-delete');
                for(var i=0;i<buttons.length;i++){
                    if(!$(buttons[i]).binded && !$(buttons[i]).hasClassName('disabled')){
                        $(buttons[i]).binded = true;
                        Event.observe(buttons[i], 'click', this.remove.bind(this));
                    }
                }
            },
            togglePriceFields : function(){
                var toogleTo = jQuery('#link-switcher1').is(':checked');
                var disableFlag = true;
                if (toogleTo) {
                    disableFlag = false;
                }
                $$('.link-prices[type="text"]').each(function(elm){ 
                    var useDefaultElm = elm.up(1).down('input[type="checkbox"]');
                    var flag = disableFlag;
                    if(useDefaultElm){ 
                        if(useDefaultElm.checked==false){
                            if (elm.hasClassName('disabled')) {
                                flag = true;
                            }
                            elm.disabled = flag;
                            if(disableFlag==true){
                                scopePrice.up(1).down('.ks-dollor-sign').addClassName("disabled");
                            }else{
                                scopePrice.up(1).down('.ks-dollor-sign').removeClassName("disabled");
                            }
                        }
                    } else{ 
                        if (elm.hasClassName('disabled')) {
                            flag = true;
                        }
                        elm.disabled = flag;
                        
                        if(disableFlag==true){
                            scopePriceField.up(0).addClassName("disabled");
                        }else{
                            scopePriceField.up(0).removeClassName("disabled");
                        }
                    }
                });
            }
        };

        /**
         * show/hide the link file and url field on condition
         */
        ksLinkFileUrlFieldShowHide = function (val, dataId) {
            if(val=="url") {
                $('downloadable_link_'+dataId+'_file').hide().removeClassName('required-entry');
                $('downloadable_link_'+dataId+'_url').show().addClassName('required-entry');
            } else {
                $('downloadable_link_'+dataId+'_url').hide().removeClassName('required-entry');
                $('downloadable_link_'+dataId+'_file').show().addClassName('required-entry');
            }
        };

        /**
         * show/hide the link sample file and url field on condition
         */
        ksLinkSampleFileUrlFieldShowHide = function (val, dataId) {
            if(val=="url") {
                $('downloadable_link_'+dataId+'_sample_file').hide();
                $('downloadable_link_'+dataId+'_sample_url').show();
            } else {
                $('downloadable_link_'+dataId+'_sample_url').hide();
                $('downloadable_link_'+dataId+'_sample_file').show();
            }
        };

        linkItems.sorting();
        linkItems.bindRemoveButtons();

        linksUploader = function (id, url) {
            (function ($) {
                $(id).fileupload({
                    dataType: 'json',
                    url: url,
                    sequentialUploads: true,
                    maxFileSize: 2000000,

                    add: function (e, data) {
                        var progressTmpl = mageTemplate(id + '-template'),
                            fileSize,
                            tmpl;

                        $.each(data.files, function (index, file) {
                            if ($(id + ' .progressbar-container').length) {
                                $(id + ' .progressbar-container').parent().remove();
                            }

                            fileSize = typeof file.size == "undefined" ?
                                $.mage.__('We could not detect a size.') :
                                byteConvert(file.size);

                            data.fileId = Math.random().toString(36).substr(2, 9);

                            tmpl = progressTmpl({
                                data: {
                                    name: file.name,
                                    size: fileSize,
                                    id: data.fileId
                                }
                            });

                            $(tmpl).appendTo(id);
                        });

                        $(this).fileupload('process', data).done(function () {
                            data.submit();
                        });
                    },
                    done: function (e, data) {
                        var progressSelector = '#' + data.fileId + ' .progressbar-container .progressbar';
                        $(progressSelector).css('width', '100%');
                        if (data.result && !data.result.hasOwnProperty('errorcode')) {
                            $(progressSelector).removeClass('upload-progress').addClass('upload-success');
                            $(id).find('input[type="file"]').addClass("ignore-validate");
                            new Downloadable.FileList(id.substr(1), null).handleUploadComplete(data.result);
                        } else {
                            $(progressSelector).removeClass('upload-progress').addClass('upload-failure');
                            var errorMsg = '<span class="file-info-error">' + data.result.error + '</span>';
                            $('#' + data.fileId + ' .file-info').append(errorMsg);
                        }
                    },
                    progress: function (e, data) {
                        var progress = parseInt(data.loaded / data.total * 100, 10);
                        var progressSelector = '#' + data.fileId + ' .progressbar-container .progressbar';
                        $(progressSelector).css('width', progress + '%');
                    },
                    fail: function (e, data) {
                        var progressSelector = '#' + data.fileId + ' .progressbar-container .progressbar';
                        $(progressSelector).removeClass('upload-progress').addClass('upload-failure');
                        if (data.result && data.result.hasOwnProperty('errorcode')) {
                            var errorMsg = '<span class="file-info-error">' + data.result.error + '</span>';
                            $('#' + data.fileId + ' .file-info').append(errorMsg);
                        }
                    }
                });
            })(jQuery);
        };

        if (jQuery('input[name="product[links_purchased_separately]"]')) {
            jQuery('input[name="product[links_purchased_separately]"]').on('change', linkItems.togglePriceFields.bind());
        }

        if($('add_link_item')) {
            Event.observe('add_link_item', 'click', linkItems.add.bind(linkItems));
        }

        <?php foreach ($block->getKsLinkData() as $item): ?>
            linkItems.add(<?= /* @noEscape */ $item->toJson() ?>);
        <?php endforeach; ?>

    });
});
</script>
