<!--
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
-->
<?php
/**
 * @var $block \Ksolves\MultivendorMarketplace\Block\Adminhtml\PriceComparison\Tabs\KsDownloadableLinks
 */
?>
<?php $ksProduct = $block->getKsSellerProduct()?>

<fieldset class="admin__fieldset downloadable-form fieldset-wrapper admin__fieldset-section" data-ui-id="downloadable-links">
    <div class="fieldset-wrapper-title"><strong class="admin__legend title"><span><?= $block->escapeHtml(__('Links')) ?></span></strong></div>
    <p class="note ks-d-none"><?= $block->escapeHtml(__('Add links to your product files here.')) ?></p>
    <div class="admin__fieldset-wrapper-content">
        <fieldset class="admin__fieldset">

            <div class="admin__field">
                <div class="admin__field-label"><label for="downloadable_links_title"><span <?= $block->escapeHtml(!$block->KsisSingleStoreMode() ? ' data-config-scope="' . __('[STORE VIEW]') . '"' : '') ?>><?= $block->escapeHtml(__('Title')) ?></span></label></div>
                <div class="admin__field-control">
                    <input type="text" class="admin__control-text" id="downloadable_links_title" name="product[links_title]" value="<?= $block->escapeHtml($block->getKsLinksTitle()) ?>" <?= ($ksProduct->getStoreId() && $block->getKsUsedDefault()) ? 'disabled="disabled"' : '' ?> data-form-part="ks_marketplace_pricecomparsion_product_edit_form" >
                    <?php if ($ksProduct->getStoreId()): ?>
                        <div class="admin__field admin__field-option">
                            <input id="link_title_default" class="admin__control-checkbox" type="checkbox" name="use_default[]" value="links_title" onclick="toggleValueElements(this, this.parentNode.parentNode)" <?= $block->getKsUsedDefault() ? 'checked="checked"' : '' ?> data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />
                            <label class="admin__field-label" for="link_title_default"><span><?= $block->escapeHtml(__('Use Default Value')) ?></span></label>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <div class="admin__field">
                <div class="admin__field-label"><label><span <?= $block->escapeHtml(!$block->KsisSingleStoreMode() ? ' data-config-scope="' . __('[GLOBAL]') . '"' : '') ?>></span></label></div>
                <div class="admin__field-control">
                    <input type="checkbox" name="product[links_purchased_separately]" value="1" class="admin__control-checkbox" id="link-switcher1" 
                    <?php if ($block->KsisProductLinksCanBePurchasedSeparately()): ?> 
                        checked="checked"
                    <?php endif; ?>
                    data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />
                    <label class="admin__field-label" for="downloadable_link_purchase_type"><span><?= $block->escapeHtml(__('Links can be purchased separately')) ?></span></label>
                </div>
            </div>

            <div class="admin__field admin__field-wide">
                <div class="admin__field-control">
                    <div class="admin__control-table-wrapper">
                        <table class="admin__dynamic-rows admin__control-table">
                            <thead>
                                <tr>
                                    <th class="col-sort"><span><?= $block->escapeHtml(__('Sort Order')) ?></span></th>
                                    <th class="col-title _required"><span><?= $block->escapeHtml(__('Title')) ?></span></th>
                                    <?php if ($block->getCanReadPrice() !== false): ?>
                                        <th class="col-price"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
                                    <?php endif; ?>
                                    <th class="col-file"><span><?= $block->escapeHtml(__('File')) ?></span></th>
                                    <th class="col-sample"><span><?= $block->escapeHtml(__('Sample')) ?></span></th>
                                    <th class="col-share"><span><?= $block->escapeHtml(__('Shareable')) ?></span></th>
                                    <th class="col-limit"><span><?= $block->escapeHtml(__('Max. Downloads')) ?></span></th>
                                    <th class="col-actions">&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody id="link_items_body">
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td class="" colspan="8"><?= $block->getKsAddButtonHtml() ?></td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>

            <div class="admin__fieldset-note admin__scope-old">
                <span><?= $block->escapeHtml(__('Alphanumeric, dash and underscore characters are recommended for filenames. Improper characters are replaced with \'_\'.')) ?></span>
            </div>

        </fieldset>
    </div>
</fieldset>

<script>
require([
    'jquery',
    'uiRegistry',
    'mage/template',
    'jquery/file-uploader',
    'mage/mage',
    'prototype',
    'mage/translate'
], function(jQuery, registry, mageTemplate){
    registry.get('downloadable', function (Downloadable) {
        var linkTemplate = '<tr>'+
            '<td class="col-sort" data-role="draggable-handle"><input data-container="link-order" type="hidden" ' +
            'name="downloadable[link][<%- ' +
            'data.id' +
            ' %>][sort_order]" ' +
            'value="<%- data.sort_order %>" class="input-text admin__control-text sort" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />' +
                '<span class="draggable-handle" title="<?= $block->escapeJs($block->escapeHtml(__('Sort Variations'))) ?>"></span>' +
            '</td>'+
            '<td class="col-title">'+
                '<input type="hidden" class="__delete__" name="downloadable[link][<%- data.id %>][is_delete]" value="" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />'+
                '<input type="hidden" name="downloadable[link][<%- data.id %>][record_id]" value="<%- data.id %>" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />'+
                '<% if (data.link_id) { %> <input type="hidden" name="downloadable[link][<%- data.id %>][link_id]" value="<%- data.link_id %>" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" /> <% } %>'+
                '<input type="text" class="required-entry input-text admin__control-text" name="downloadable[link][<%- data.id %>][title]" value="<%- data.title %>" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />'+
                <?php if ($ksProduct->getStoreId()): ?>
                    '<div class="admin__field admin__field-option">'+
                    '<input type="checkbox" id="downloadable_link_<%- data.id %>_title" name="downloadable[link][<%- data.id %>][use_default_title]" value="1" class="admin__control-checkbox" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />'+
                    '<label for="downloadable_link_<%- data.id %>_title" class="admin__field-label"><span><?= $block->escapeJs($block->escapeHtml(__('Use Default Value'))) ?></span></label>'+
                    '</div>' +
                <?php endif; ?>
                <?php if ($block->getCanReadPrice() == false): ?>
                    '<input type="hidden" id="downloadable_link_<%- data.id %>_price_value" class="link-prices" name="downloadable[link][<%- data.id %>][price]" value="0" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />' +
                    <?php if ($ksProduct->getStoreId() && $block->getKsIsPriceWebsiteScope()): ?>
                    '<input type="hidden" id="downloadable_link_<%- data.id %>_price" name="downloadable[link][<%- data.id %>][use_default_price]" value="1" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />' +
                    <?php endif; ?>
                <?php endif; ?>
            '</td>'+
            <?php if ($block->getCanReadPrice() !== false): ?>
                '<td class="col-price">'+
                    '<div class="admin__control-addon">' +
                        '<input type="text" id="downloadable_link_<%- data.id %>_price_value" class="input-text admin__control-text validate-number link-prices<?php if ($block->getCanEditPrice() === false): ?> disabled<?php endif; ?>" name="downloadable[link][<%- data.id %>][price]" value="<%- data.price %>" <?php if ($block->getCanEditPrice() === false): ?> disabled="disabled"<?php endif; ?> data-form-part="ks_marketplace_pricecomparsion_product_edit_form" /> ' +
                        '<label class="admin__addon-prefix"><span><?= $block->escapeHtml($block->getKsBaseCurrencySymbol($ksProduct->getStoreId())) ?></span></label>' +
                    '</div>' +
                    <?php if ($ksProduct->getStoreId() && $block->getKsIsPriceWebsiteScope()): ?>
                        '<div class="admin__field admin__field-option">'+
                            '<input type="checkbox" id="downloadable_link_<%- data.id %>_price" name="downloadable[link][<%- data.id %>][use_default_price]" value="1"<?php if ($block->getCanEditPrice() === false): ?> disabled="disabled"<?php endif; ?> class="admin__control-checkbox" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />'+
                            '<label for="downloadable_link_<%- data.id %>_price" class="admin__field-label"><span><?= $block->escapeJs($block->escapeHtml(__('Use Default Value'))) ?></span></label>' +
                        '</div>' +
                    <?php endif; ?>
                '</td>' +
            <?php endif; ?>
            '<td class="col-file admin__control-fields">'+
                '<fieldset class="admin__field">'+
                    '<div class="admin__field-control admin__control-fields admin__field-option">'+
                        '<div class="admin__field">'+
                            '<div class="admin__field-label ks-d-none">'+
                            '</div>'+
                            '<div class="admin__field-control">'+
                                '<select class="admin__control-select" name="downloadable[link][<%- data.id %>][type]" id="downloadable_link_<%- data.id %>_type" onchange="ksLinkFileUrlFieldShowHide(this.value, <%- data.id %>)" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />' +
                                    '<option value="file" id="downloadable_link_<%- data.id %>_file_type" <%- data.file_selected %> ><?= $block->escapeJs($block->escapeHtml(__('Upload File'))) ?></option>'+
                                    '<option value="url" id="downloadable_link_<%- data.id %>_url_type" <%- data.url_selected %> ><?= $block->escapeJs($block->escapeHtml(__('URL'))) ?></option>'+
                                '</select>' +
                                '<input class="ks-d-none" id="downloadable_link_<%- data.id %>_file" type="file" name="<?=  $block->escapeJs($block->escapeHtmlAttr($block->getKsFileFieldName('links'))) ?>">' +
                            '</div>'+
                        '</div>'+
                        '<input type="hidden" class="validate-downloadable-file" id="downloadable_link_<%- data.id %>_file_save" name="downloadable[link][<%- data.id %>][file]" value="<%- data.file_save %>" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />'+
                        '<div class="admin__field ks-mt-2">'+   
                            '<div class="admin__field-label ks-d-none">'+
                            '</div>'+ 
                            '<div class="admin__field-control">'+
                                '<div class="admin__field-control">'+
                                    '<div id="downloadable_link_<%- data.id %>_file" class="file-uploader" <% if (data.link_type == "url") { %> style="display:none" <% } %> >'+
                                        '<div class="file-uploader-summary ks-file-uploader-name">'+
                                            '<div" id="downloadable_link_<%- data.id %>_file-old" class="file-uploader-filename file-row-info"></div>'+
                                        '</div>'+
                                        '<div id="downloadable_link_<%- data.id %>_file-new" class="file-row-info new-file"></div>'+
                                        '<div class="file-uploader-area fileinput-button form-buttons">'+
                                            '<input id="downloadable_link_<%- data.id %>_file" type="file" name="<?=  $block->escapeJs($block->escapeHtmlAttr($block->getKsFileFieldName('links'))) ?>">' +
                                            '<label for="downloadable_link_0_file" class="file-uploader-button action-secondary"><?= $block->escapeJs($block->escapeHtml(__('Browse Files...'))) ?></label>' +
                                            '<script>' +
                                                'linksUploader("#downloadable_link_<%- data.id %>_file", "<?=  $block->escapeJs($block->escapeUrl($block->getKsUploadUrl('links'))) ?>"); ' +
                                            '</scr'+'ipt>'+
                                        '</div>'+
                                    '</div>'+
                                    '<input type="text" class="ks-mt-2 validate-downloadable-url validate-url admin__control-text" name="downloadable[link][<%- data.id %>][link_url]" id="downloadable_link_<%- data.id %>_url" value="<%- data.link_url %>" <% if (data.link_type == "file") { %> style="display:none" <% } %> placeholder="<?= $block->escapeJs($block->escapeHtmlAttr(__('URL'))) ?>" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />'+
                                '</div>'+
                            '</div>'+ 
                        '</div>'+
                    '</div>'+
                '</fieldset>'+
                '<div>'+
                    '<span id="downloadable_link_<%- data.id %>_link_container"></span>'+
                '</div>'+
            '</td>'+
            '<td class="col-sample admin__control-fields">'+
                '<fieldset class="admin__field">'+
                    '<div class="admin__field admin__field-option admin__field-control admin__control-fields">'+
                        '<div class="admin__field">'+
                            '<div class="admin__field-label ks-d-none">'+
                            '</div>'+ 
                            '<div class="admin__field-control">'+
                                '<select class="admin__control-select" name="downloadable[link][<%- data.id %>][sample][type]" id="downloadable_link_<%- data.id %>_sample_type" onchange="ksLinkSampleFileUrlFieldShowHide(this.value, <%- data.id %>)" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />' +
                                    '<option value="file" id="downloadable_link_<%- data.id %>_sample_file_type" <%- data.sample_file_selected %> ><?= $block->escapeJs($block->escapeHtml(__('Upload File'))) ?></option>'+
                                    '<option value="url" id="downloadable_link_<%- data.id %>_sample_url_type" <%- data.sample_url_selected %> ><?= $block->escapeJs($block->escapeHtml(__('URL'))) ?></option>'+
                                '</select>' +
                                '<input class="ks-d-none" id="downloadable_link_<%- data.id %>_sample_file" type="file" name="<?= $block->escapeJs($block->escapeHtmlAttr($block->getKsFileFieldName('link_samples'), '"')) ?>" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" >' +
                            '</div>'+ 
                        '</div>'+
                        '<input type="hidden" id="downloadable_link_<%- data.id %>_sample_file_save" name="downloadable[link][<%- data.id %>][sample][file]" value="<%- data.sample_file_save %>" class="validate-downloadable-file" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />'+
                        '<div class="admin__field">'+  
                            '<div class="admin__field-label ks-d-none">'+
                            '</div>'+   
                            '<div class="admin__field-control">'+ 
                                '<div class="admin__field-control">'+ 
                                    '<div id="downloadable_link_<%- data.id %>_sample_file" class="ks-mt-2 file-uploader" <% if (data.sample_type == "url") { %> style="display:none" <% } %> >'+
                                        '<div id="downloadable_link_<%- data.id %>_sample_file-old" class="file-row-info"></div>'+
                                        '<div id="downloadable_link_<%- data.id %>_sample_file-new" class="file-row-info new-file"></div>'+
                                        '<div class="fileinput-button form-buttons file-uploader-area">'+
                                            '<input id="downloadable_link_<%- data.id %>_sample_file" type="file" name="<?= $block->escapeJs($block->escapeHtmlAttr($block->getKsFileFieldName('link_samples'), '"')) ?>" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" >' +
                                            '<label for="downloadable_link_0_sample_file" class="file-uploader-button action-secondary"><?= $block->escapeJs($block->escapeHtml(__('Browse Files...'))) ?></span>' +
                                            '<script>'+
                                            'linksUploader("#downloadable_link_<%- data.id %>_sample_file", "<?=  $block->escapeJs($block->escapeUrl($block->getKsUploadUrl('link_samples'))) ?>"); ' +
                                            '</scr'+'ipt>'+
                                        '</div>'+
                                    '</div>'+
                                    '<input type="text" class="ks-mt-2 validate-downloadable-url validate-url admin__control-text" name="downloadable[link][<%- data.id %>][sample][url]" value="<%- data.sample_url %>" id="downloadable_link_<%- data.id %>_sample_url" <% if (data.sample_type == "file") { %> style="display:none" <% } %> placeholder="<?= $block->escapeJs($block->escapeHtmlAttr(__('URL'))) ?>" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />'+
                                '</div>'+
                            '</div>'+
                        '</div>'+
                    '</div>'+
                    '<div>'+
                        '<span id="downloadable_link_<%- data.id %>_sample_container"></span>'+
                    '</div>'+
                '</fieldset>'+
            '</td>'+
            '<td class="col-share">'+
                '<select id="downloadable_link _<%- data.id %>_shareable" class="admin__control-select" name="downloadable[link][<%- data.id %>][is_shareable]" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" >'+
                    '<option value="1"><?= $block->escapeJs($block->escapeHtml(__('Yes'))) ?></option>'+
                    '<option value="0"><?= $block->escapeJs($block->escapeHtml(__('No'))) ?></option>'+
                    '<option value="2" selected="selected"><?= $block->escapeJs($block->escapeHtml(__('Use config'))) ?></option>'+
                '</select>'+
            '</td>'+
            '<td class="col-limit">' +
                '<input type="text" id="downloadable_link_<%- data.id %>_downloads" name="downloadable[link][<%- data.id %>][number_of_downloads]" class="input-text validate-zero-or-greater admin__control-text downloads" value="<%- data.number_of_downloads %>" data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />'+
                '<div class="admin__field admin__field-option">' +
                    '<input type="checkbox" class="admin__control-checkbox" id="downloadable_link_<%- data.id %>_is_unlimited" name="downloadable[link][<%- data.id %>][is_unlimited]" value="1" <%- data.is_unlimited %> data-form-part="ks_marketplace_pricecomparsion_product_edit_form" />' +
                    '<label for="downloadable_link_<%- data.id %>_is_unlimited" class="ks-mt-2 admin__field-label"><span><?= $block->escapeJs($block->escapeHtml(__('Unlimited'))) ?></span></label>' +
                '</div>' +
            '</td>'+
            '<td class="col-action">'+
                '<button id="downloadable_link_<%- data.id %>_delete_button" type="button" class="action-delete" title="<?= $block->escapeJs($block->escapeHtmlAttr(__('Delete'))) ?>"><span><?= $block->escapeJs($block->escapeHtml(__('Delete'))) ?></span></button>'+
            '</td>'+
        '</tr>';

        var linkItems = {
            tbody : $('link_items_body'),
            templateText : linkTemplate,
            itemCount : 0,
            add : function(data) {
                alertAlreadyDisplayed = false;
                this.template = mageTemplate(this.templateText);

                if(!data.link_id){
                    data = {};
                    data.link_type = 'file';
                    data.sample_type = 'none';
                    data.number_of_downloads = '<?= $block->escapeJs($block->getKsConfigMaxDownloads()) ?>';
                    data.sort_order = this.itemCount + 1;
                }

                data.id = this.itemCount;

                if (data.link_type == 'url') {
                    data.url_selected = ' selected="selected"';
                } else if (data.link_type == 'file') {
                    data.file_selected = ' selected="selected"';
                }
                if (data.sample_type == 'url') {
                    data.sample_url_selected = ' selected="selected"';
                } else if (data.sample_type == 'file') {
                    data.sample_file_selected = ' selected="selected"';
                }

                var rowElement = Element.insert(this.tbody, {
                    'bottom': this.template({data: data})
                });

                scopeTitle = $('downloadable_link_'+data.id+'_title');
                if (scopeTitle) {
                    Event.observe(scopeTitle, 'click', function(event){
                        scopeElm = $(Event.findElement(event, 'input'));
                        titleField = scopeElm.up(0).down('input[type="text"]');
                        if (scopeElm.checked == true) {
                            titleField.disabled = true;
                        } else {
                            titleField.disabled = false;
                        }
                    });
                }
                /*if (!data.store_title && scopeTitle) {
                    scopeTitle.up(0).down('input[type="text"]').disabled = true;
                    scopeTitle.checked = true;
                }*/

                scopePrice = $('downloadable_link_'+data.id+'_price');
                if (scopePrice) {
                    Event.observe(scopePrice, 'click', function(event){
                        scopeElm = $(Event.findElement(event, 'input'));
                        priceField = scopeElm.up(0).down('input[type="text"]');
                        if (scopeElm.checked == true) {
                            priceField.disabled = true;
                        } else {
                            priceField.disabled = false;
                        }
                    });
                }
                if (!data.website_price && scopePrice) {
                    scopePrice.up(0).down('input[type="text"]').disabled = true;
                    scopePrice.checked = true;
                }
                downloadsElm = $('downloadable_link_'+data.id+'_downloads');
                isUnlimitedElm = $('downloadable_link_'+data.id+'_is_unlimited');
                if (data.is_unlimited) {
                    downloadsElm.disabled = true;
                }
                Event.observe(isUnlimitedElm, 'click', function(event){
                    elm = Event.element(event);
                    elm.up('td').down('input[type="text"].downloads').disabled = elm.checked;
                });

                if (data.is_shareable) {
                    options = $('downloadable_link _'+data.id+'_shareable').options;
                    for (var i=0; i < options.length; i++) {
                        if (options[i].value == data.is_shareable) {
                            options[i].selected = true;
                        }
                    }
                }

                sampleUrl = $('downloadable_link_'+data.id+'_sample_url_type');
                linkUrl = $('downloadable_link_'+data.id+'_url_type');

                if (!data.file_save) {
                    data.file_save = [];
                }
                if (!data.sample_file_save) {
                    data.sample_file_save = [];
                }

                // link sample file
                new Downloadable.FileUploader(
                    'linkssample',
                    'linkssample_'+data.id,
                    sampleUrl.up('td'),
                    'downloadable[link]['+data.id+'][sample]',
                    data.sample_file_save,
                    'downloadable_link_'+data.id+'_sample_file',
                    <?= /* @noEscape */ $block->getKsConfigJson('link_samples') ?>
                );
                // link file
                new Downloadable.FileUploader(
                    'links',
                    'links_'+data.id,
                    linkUrl.up('td'),
                    'downloadable[link]['+data.id+']',
                    data.file_save,
                    'downloadable_link_'+data.id+'_file',
                    <?= /* @noEscape */ $block->getKsConfigJson() ?>
                );

                linkFile = $('downloadable_link_'+data.id+'_file_type');
                linkFile.advaiceContainer = 'downloadable_link_'+data.id+'_link_container';
                linkUrl.advaiceContainer = 'downloadable_link_'+data.id+'_link_container';
                $('downloadable_link_'+data.id+'_file_save').advaiceContainer = 'downloadable_link_'+data.id+'_link_container';

                sampleFile = $('downloadable_link_'+data.id+'_sample_file_type');

                this.itemCount++;
                this.togglePriceFields();
                this.bindRemoveButtons();
            },
            sorting: function () {
                var list = jQuery(this.tbody);
                list.sortable({
                    axis: 'y',
                    handle: '[data-role=draggable-handle]',
                    items: 'tr',
                    update: function (event, data) {
                        list.find('[data-container=link-order]').each(function (i, el) {
                            jQuery(el).val(i + 1);
                        });
                    },
                    tolerance: 'pointer'
                });
            },
            remove : function(event){
                var element = $(Event.findElement(event, 'tr'));

                if(element){
                    element.remove();
                }
            },
            bindRemoveButtons : function(){
                var buttons = $$('tbody#link_items_body .action-delete');
                for(var i=0;i<buttons.length;i++){
                    if(!$(buttons[i]).binded && !$(buttons[i]).hasClassName('disabled')){
                        $(buttons[i]).binded = true;
                        Event.observe(buttons[i], 'click', this.remove.bind(this));
                    }
                }
            },
            togglePriceFields : function(){
                var toogleTo = jQuery('#link-switcher1').is(':checked');
                var disableFlag = true;
                if (toogleTo) {
                    disableFlag = false;
                }
                $$('.link-prices[type="text"]').each(function(elm){
                    var flag = disableFlag;
                    if (elm.hasClassName('disabled')) {
                        flag = true;
                    }
                    elm.disabled = flag;
                });
            }
        };

        /**
         * show/hide the link file and url field on condition
         */
        ksLinkFileUrlFieldShowHide = function (val, dataId) {
            if(val=="url") {
                $('downloadable_link_'+dataId+'_file').hide();
                $('downloadable_link_'+dataId+'_url').show();
            } else {
                $('downloadable_link_'+dataId+'_url').hide();
                $('downloadable_link_'+dataId+'_file').show();
            }
        };

        /**
         * show/hide the link sample file and url field on condition
         */
        ksLinkSampleFileUrlFieldShowHide = function (val, dataId) {
            if(val=="url") {
                $('downloadable_link_'+dataId+'_sample_file').hide();
                $('downloadable_link_'+dataId+'_sample_url').show();
            } else {
                $('downloadable_link_'+dataId+'_sample_url').hide();
                $('downloadable_link_'+dataId+'_sample_file').show();
            }
        };

        linkItems.sorting();
        linkItems.bindRemoveButtons();

        linksUploader = function (id, url) {
            (function ($) {

                $(id).fileupload({
                    dataType: 'json',
                    url: url,
                    sequentialUploads: true,
                    maxFileSize: 2000000,
                    formData: {
                        'form_key': window.FORM_KEY
                    },
                    add: function (e, data) {

                        var progressTmpl = mageTemplate(id + '-template'),
                            fileSize,
                            tmpl;
        
                        $.each(data.files, function (index, file) {
                            
                            if ($(id + ' .progressbar-container').length) {
                                $(id + ' .progressbar-container').parent().remove();
                            }

                            fileSize = typeof file.size == "undefined" ?
                                $.mage.__('We could not detect a size.') :
                                byteConvert(file.size);

                            data.fileId = Math.random().toString(36).substr(2, 9);

                            tmpl = progressTmpl({
                                data: {
                                    name: file.name,
                                    size: fileSize,
                                    id: data.fileId
                                }
                            });

                            $(tmpl).appendTo(id);
                        });

                        $(this).fileupload('process', data).done(function () {

                            data.submit();
                        });
                    },
                    done: function (e, data) {
                        /*console.log(data); debugger;*/
                        var progressSelector = '#' + data.fileId + ' .progressbar-container .progressbar';
                        $(progressSelector).css('width', '100%');
                        if (data.result && !data.result.hasOwnProperty('errorcode')) {
                            $(progressSelector).removeClass('upload-progress').addClass('upload-success');
                            new Downloadable.FileList(id.substr(1), null).handleUploadComplete(data.result);
                        } else {
                            $(progressSelector).removeClass('upload-progress').addClass('upload-failure');
                            var errorMsg = '<span class="file-info-error">' + data.result.error + '</span>';
                            $('#' + data.fileId + ' .file-info').append(errorMsg);
                        }
                    },
                    progress: function (e, data) {
                        var progress = parseInt(data.loaded / data.total * 100, 10);
                        var progressSelector = '#' + data.fileId + ' .progressbar-container .progressbar';
                        $(progressSelector).css('width', progress + '%');
                    },
                    fail: function (e, data) {
                        var progressSelector = '#' + data.fileId + ' .progressbar-container .progressbar';
                        $(progressSelector).removeClass('upload-progress').addClass('upload-failure');
                        if (data.result && data.result.hasOwnProperty('errorcode')) {
                            var errorMsg = '<span class="file-info-error">' + data.result.error + '</span>';
                            $('#' + data.fileId + ' .file-info').append(errorMsg);
                        }
                    }
                });
            })(jQuery);
        };

        if (jQuery('input[name="product[links_purchased_separately]"]')) {
            jQuery('input[name="product[links_purchased_separately]"]').on('change', linkItems.togglePriceFields.bind());
        }

        if($('add_link_item')) {
            Event.observe('add_link_item', 'click', linkItems.add.bind(linkItems));
        }

        <?php foreach ($block->getKsLinkData() as $ksItem): ?>
            linkItems.add(<?= /* @noEscape */ $ksItem->toJson() ?>);
        <?php endforeach; ?>

    });
});
</script>