<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
?>

<div class="ks-grid-pager mt-3 mb-3">
    <div class="admin__data-grid-pager-wrap">
        <div class="ks-pagination-sel">
            <select class="ks-pager-select">
                <option value="5" selected="selected">5</option>
                <option value="20">20</option>
                <option value="30">30</option>
                <option value="50">50</option>
                <option value="100">100</option>
                <option value="200">200</option>
                <option value="500">500</option>
            </select>
        </div>
        <label class="ks-perpage-text admin__control-support-text">per page</label>
        <div class="admin__data-grid-pager">
            <button class="ks-action-previous action-previous" type="button" title="Previous Page"></button>
            <input class="ks-current-page admin__control-text" type="number" value="1"/>
            <label class="ks-pager-text admin__control-support-text"></label>
            <button class="ks-action-next action-next" type="button" title="Next Page"></button>
        </div>
    </div>
</div>
   
    