<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/* @var Ksolves\MultivendorMarketplace\Block\Order\CreditMemo\View\KsForm */

$ksCreditMemo = $block->getKsCreditmemo();
$ksOrder = $block->getKsOrder();
?>

<!-- credit memo view page start --> 
<div class="ks-memo-create-page">
    <div class="ks-page-card">
        <?= $block->getChildHtml('multivendor_order_account_address_info') ?>

        <!-- Order view billing shipping start-->
        <section class="order-view-billing-shipping mb-5">

            <!-- Order tab section title start -->
            <div class="ks-tab-content-title">
                <span><?= $block->escapeHtml(__('Payment &amp; Shipping Method')) ?></span>
            </div>
            <!-- Order tab section title end -->

            <div>
                <div class=" order-payment-method<?php if ($ksOrder->getIsVirtual()) : ?> order-payment-method-virtual<?php endif; ?>">
                    <?php /*Billing Address */ ?>

                    <!-- Order tab div title start -->
                    <div class="ks-div-title mb-3">
                        <span><?= $block->escapeHtml(__('Payment Information')) ?></span>
                    </div>
                    <!-- Order tab div title end -->

                    <div>
                        <div class="order-payment-method-title"><?= $block->getChildHtml('order_payment') ?></div>
                        <div class="order-payment-currency">
                            <?= $block->escapeHtml(__('The order was placed using %1.', $ksOrder->getOrderCurrencyCode())) ?>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Order view billing shipping end -->

        <!-- Item refund table start -->
        <section class="mb-5">

            <!-- Order tab section title start -->
            <div class="ks-tab-content-title">
                <span><?= $block->escapeHtml(__('Items Refunded')) ?></span>
            </div>
            <!-- Order tab section title end -->

            <div id="creditmemo_item_container">
                <?= $block->getChildHtml('creditmemo_items') ?>
            </div>
        </section>
        <!-- Item refund table start -->

        <!-- Order total start -->
        <section>
            <?php if($ksCreditMemo->getKsApprovalStatus()==2):?>
                <form method="post" action="<?= $block->getKsReSubmitUrl();?>">
            <?php endif;?>
            <!-- Order tab section title start -->
            <div class="ks-tab-content-title">
                <span><?= $block->escapeHtml(__('Order Total')); ?></span>
            </div>
            <!-- Order tab section title end -->

            <div class="order-comments-history col-md-12">
                <div class="row">

                    <!-- Credit memo history start -->
                    <div class="col-md-6 pl-0">  

                        <!-- Order tab div title start -->
                        <div class="ks-div-title mb-3">
                            <span><?= $block->escapeHtml(__('CreditMemo History')); ?></span>
                        </div>
                        <!-- Order tab div title end -->

                        <div><?= $block->getChildHtml('order_comments'); ?></div>
                    </div>
                    <!-- Credit memo history end -->

                    <!-- Credit memo tools start -->
                    <div class="col-md-6 pr-0">

                        <!-- Order tab div title start -->
                        <div class="ks-div-title">
                            <span><?= $block->escapeHtml(__('CreditMemo Totals')); ?></span>
                        </div>
                        <!-- Order tab div title end -->

                        <div class="ks-sales-table"><?= $block->getChildHtml('creditmemo_totals'); ?></div>
                    </div>
                    <!-- Credit memo tools end -->

                </div>
            </div>
            <?php if($ksCreditMemo->getKsApprovalStatus()==2):?>
                </form>
            <?php endif;?>
        </section>
        <!-- Order total end -->

    </div>
</div>
<!-- credit memo view page end --> 