<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/** @var \Ksolves\MultivendorMarketplace\Block\Order\CreditMemo\Create\KsItems $block */
$ksProductHelper = $block->getData('ksProductHelper');
$ksOrderHelper = $block->getData('ksOrderHelper');
$commentText = $block->getKsCreditmemo()->getCommentText();
$ksBaseSubtotalAmount = 0;
$ksBaseTaxAmount = 0;
$ksBaseDiscountAmount = 0;
$ksBaseItemCommission = 0;
$ksBaseTotalPaid = 0;
$ksBaseTotalRefund = 0;
$ksTotalCommission =0;
$ksTotalEarning=0;
$ksSubtotalAmount=0;
$ksDiscountAmount=0;
$ksTaxAmount=0;
$ksBaseTotalCommission =0;
$ksBaseTotalEarning=0;
$ksBaseWeeeTax = 0;
$ksWeeeTax = 0;
$ksShowStoreCurrency = $block->canKsShowOrderCurrencyValue();
?>

<!-- create credit memo page start -->
<div class="creditmemo-container">

    <!-- Memo tab div title start -->
    <div class="ks-tab-content-title">
        <span class="title"><?= $block->escapeHtml(__('Items to Refund')) ?></span>
    <!-- Memo tab div title end -->
    </div>

    <div class="ks-simple-table">
        <table class="data-table order-creditmemo-tables table" id="ks-creditmemo">
            <?php $creditmemo = $block->getKsCreditmemo();?>
            <thead>
                <tr class="headings">
                    <th class="col-product"><span><?= $block->escapeHtml(__('Product')) ?></span></th>
                    <th class="col-price"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
                    <th class="col-ordered-qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></th>
                    <?php if ($block->canKsReturnToStock()): ?>
                        <th class="col-return-to-stock"><span><?= $block->escapeHtml(__('Return to Stock')) ?></span></th>
                    <?php endif; ?>
                    <th class="col-refund"><span><?= $block->escapeHtml(__('Qty to Refund')) ?></span></th>
                    <th class="col-subtotal"><span><?= $block->escapeHtml(__('Subtotal')) ?></span></th>
                    <th class="col-tax-amount"><span><?= $block->escapeHtml(__('Tax Amount')) ?></span></th>
                    <th class="col-discont"><span><?= $block->escapeHtml(__('Discount Amount')) ?></span></th>
                    <th class="col-total last"><span><?= $block->escapeHtml(__('Row Total')) ?></span></th>
                </tr>
            </thead>                       
            <?php $ks_items = $block->getKsCreditmemo()->getAllItems() ?>
            <?php foreach ($ks_items as $ks_item): ?>                        
                <?php if ($ks_item->getOrderItem()->getParentItem()):
                continue;?>
                
                <?php $ksOrderItem = $ks_item->getOrderItem(); ?>
                <?php  elseif($ksProductHelper->isKsSellerProduct($ks_item->getOrderItem()->getProductId()) && ($ksOrderHelper->getKsRefundableQty($ks_item->getOrderItem()->getId()))):?>
                        <?php if($ks_item->getOrderItem()->getProductType()==\Magento\Catalog\Model\Product\Type::TYPE_BUNDLE):?>
                        <?= $block->getLayout()->createBlock('Ksolves\MultivendorMarketplace\Block\Order\CreditMemo\Create\KsItems')->setKsBundleItem($ks_item)->setTemplate('Ksolves_MultivendorMarketplace::order/creditmemo/create/bundle/items-renderer.phtml')->toHtml(); ?>

                        <?php else:?>
                        <tr id="order-item-row-4" >
                            <td>
                                <span>
                                    <?= $block->escapeHtml(__($ks_item->getName())) ?></span></br>
                                <span class="ks-order-item-sku"><?= $block->escapeHtml("SKU: ".__($ks_item->getSku())) ?></span>
                                <!-- get ordered product attributes -->
                                <span><?= $block->escapeHtml($block->getKsCreditMemoItemAttrValue($ks_item->getOrderItem()->getId())) ?></span>
                                <?php if ($ks_item->getOrderItem()->getProductType()=='downloadable' && $block->getKsDownloadableLinkTitle($ks_item->getOrderItem())):?>
                                        <div class="ks-download-link-data">
                                            <span><?= $block->escapeHtml($block->getKsDownloadableLinkTitle($ks_item->getOrderItem())) ?></span>
                                            <?php foreach ($block->getKsDownloadableItemData($ks_item->getOrderItem())->getPurchasedItems() as $ksLink): ?>
                                                <span><?= $block->escapeHtml($ksLink->getLinkTitle()) ?>
                                                    (<?= $block->escapeHtml($ksLink->getNumberOfDownloadsBought() ? 
                                                    $ksLink->getNumberOfDownloadsBought() : __('Unlimited')) ?>)
                                                </span>
                                            <?php endforeach; ?>
                                        </div>
                                    <?php endif;?>                  
                            </td>
                            <td>
                                <span><?= $block->formatValue($ks_item->getBasePrice() + $ks_item->getBaseWeeeTaxAppliedAmount()) ?></span>
                                <br>
                                <?php if($ksShowStoreCurrency):?>
                                        <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($ks_item->getPrice() + $ks_item->getWeeeTaxAppliedAmount())?></span>
                                <?php endif;?>
                                <?php if ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ks_item)) : ?>
                                        
                                    <span>
                                        <?php foreach ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ks_item) as $ksTax) : ?>
                                            <span class="nobr"><?= $block->escapeHtml($ksTax['title']) ?>:<?= $block->formatValue($ksTax['base_amount']) ?></span>
                                            <br>
                                            <?php if($ksShowStoreCurrency):?>
                                                <span><?= $block->formatToOrderCurrency($ksTax['amount'])?></span>
                                            <?php endif;?>                                                  
                                        <?php endforeach; ?>
                                    </span>
                                <?php endif; ?>
                            </td>
                            <td>
                                <!-- get qty of ordered product -->
                                <p>
                                    <span><?= $block->escapeHtml(__('Ordered: '.(float) $ks_item->getOrderItem()->getQtyOrdered())) ?></span>
                                </p> 
                                <!-- check qty of invoiced product -->
                                <?php if ($ks_item->getOrderItem()->getQtyInvoiced() != 0) : ?>
                                <p>
                                    <span><?= $block->escapeHtml(__('Invoiced: '.(float) $ks_item->getOrderItem()->getQtyInvoiced())) ?></span>
                                </p>
                        <?php endif; ?>
                        <!-- check qty of shipped product -->
                        <?php if ($ks_item->getOrderItem()->getQtyShipped() != 0) : ?>
                            <p>
                                <span><?= $block->escapeHtml(__('Shipped: '.(float) $ks_item->getOrderItem()->getQtyShipped())) ?></span>
                            </p>
                        
                         <?php endif;?>
                        <!-- check qty of refunded product -->
                         <?php if ($ks_item->getOrderItem()->getQtyRefunded() != 0) : ?>
                            <p>
                                <span><?= $block->escapeHtml(__('Refunded: '.(float) $ks_item->getOrderItem()->getQtyRefunded())) ?></span>
                            </p>
                        <?php endif; ?>
                        <!-- check qty of canceled product -->
                        <?php if ($ks_item->getOrderItem()->getQtyCanceled() != 0) : ?>
                            <p>
                                <span><?= $block->escapeHtml(__('Canceled: '.(float) $ks_item->getOrderItem()->getQtyCanceled())) ?></span>
                            </p>
                        <?php endif; ?>
                        </td>
                        <?php if ($block->canKsReturnItemsToStock($ks_item)) : ?>
                            <td class="col-return-to-stock">
                                <?php if ($block->canKsReturnItemsToStock($ks_item)) : ?>
                                    <input type="checkbox"
                                    name="creditmemo[return_to_stock][<?= (int) $ks_item->getOrderItemId() ?>][back_to_stock]"
                                    value="1"<?php if ($ks_item->getBackToStock()) : ?> checked<?php endif; ?>/>
                                    <label></label>
                                <?php endif; ?>
                            </td>
                        <?php endif; ?>
                        <td>
                            <?php if($ks_item->getOrderItem()->getIsQtyDecimal()):?>
                                <input type="text" class="ks-creditmemo-item-qty ks-max-w-60" name="creditmemo[items][<?= (int) $ks_item->getOrderItemId() ?>][qty]" item-id="items[<?=$ks_item->getOrderItem()->getId();?>]" value="<?= $ks_item->getQty(); ?>" >
                            <!-- creditmemo[items][<?= (int) $_item->getOrderItemId() ?>][qty] -->
                            <?php else:?>
                               <input type="text" class="ks-creditmemo-item-qty ks-max-w-60" name="creditmemo[items][<?= (int) $ks_item->getOrderItemId() ?>][qty]"  item-id="<?=$ks_item->getOrderItem()->getId();?>" value="<?= floor($ks_item->getQty()); ?>" >                                
                            <?php endif;?>
                        </td>
                        <td>
                            <span><?= $block->formatValue($ks_item->getBaseRowTotal() + ($ks_item->getBaseWeeeTaxAppliedAmount()* $ks_item->getQty())) ?></span>
                            <br>
                            <?php if($ksShowStoreCurrency):?>
                                    <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($ks_item->getRowTotal() + ($ks_item->getWeeeTaxAppliedAmount()* $ks_item->getQty()))?></span>
                            <?php endif;?>
                            <?php if ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ks_item)) : ?>
                            
                                <span>
                                    <?php foreach ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ks_item) as $ksTax) : ?>
                                        <span class="nobr"><?= $block->escapeHtml($ksTax['title']) ?>:<?= $block->formatValue($ksTax['base_row_amount']) ?></span>
                                        <br>
                                        <?php if($ksShowStoreCurrency):?>
                                            <span><?= $block->formatToOrderCurrency($ksTax['row_amount'])?></span>
                                        <?php endif;?>                                                  
                                    <?php endforeach; ?>
                                </span>
                            <?php endif; ?>
                        </td>
                        <td>
                            <span><?= $block->formatValue($ks_item->getBaseTaxAmount()) ?></span>
                            <br>
                            <?php if($ksShowStoreCurrency):?>
                                    <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($ks_item->getTaxAmount())?></span>
                                <?php endif;?>
                        </td>
                        <td>
                            <span><?= $block->formatValue($ks_item->getBaseDiscountAmount()) ?></span>
                            <br>
                            <?php if($ksShowStoreCurrency):?>
                                    <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($ks_item->getDiscountAmount())?></span>
                            <?php endif;?>
                        </td>
                        <td>
                            <span><?= $block->formatValue($ks_item->getBaseRowTotal()-$ks_item->getBaseDiscountAmount() + $ksOrderHelper->ksCalcItemBaseTaxAmt($ks_item->getOrderItem(),$ks_item->getQty()) + ($ks_item->getBaseWeeeTaxAppliedAmount()* $ks_item->getQty())) ?></span>
                            <br>
                            <?php if($ksShowStoreCurrency):?>
                                <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($ks_item->getRowTotal()-$ks_item->getDiscountAmount() + $ksOrderHelper->ksCalcItemTaxAmt($ks_item->getOrderItem(),$ks_item->getQty()) + ($ks_item->getWeeeTaxAppliedAmount()* $ks_item->getQty()))?></span>
                            <?php endif;?>
                        </td>
                     </tr>
                 <?php endif;?>
                    <?php endif;?>
                    <?php endforeach; ?> 
        </table>                
    </div>
    <?php
        foreach($creditmemo->getAllItems() as $ks_item){
            if (!$ks_item->getOrderItem()->isDummy()) {
                $ksTotalCommission += $ksOrderHelper->getKsItemCommission($ks_item->getOrderItemId(),$ks_item->getQty());
                $ksBaseTotalCommission += $ksOrderHelper->getKsItemBaseCommission($ks_item->getOrderItemId(),$ks_item->getQty());                       
            }
            $ksBaseWeeeTax += $ks_item->getBaseWeeeTaxAppliedAmount()* $ks_item->getQty();
            $ksWeeeTax += $ks_item->getWeeeTaxAppliedAmount()* $ks_item->getQty();
        }
        $ksTotalEarning += $creditmemo->getGrandTotal()-$creditmemo->getShippingTaxAmount()-$creditmemo->getShippingAmount() - $ksTotalCommission + ($creditmemo->getBaseShippingAmount()? $creditmemo->getOrder()->getShippingDiscountAmount():0 );
        $ksTotalEarning = $ksTotalEarning>0 ? $ksTotalEarning : 0;
        $ksBaseTotalEarning += $creditmemo->getBaseGrandTotal()-$creditmemo->getBaseShippingTaxAmount()-$creditmemo->getBaseShippingAmount() - $ksBaseTotalCommission + ($creditmemo->getBaseShippingAmount()? $creditmemo->getOrder()->getBaseShippingDiscountAmount():0 );
        $ksBaseTotalEarning = $ksBaseTotalEarning>0 ? $ksBaseTotalEarning : 0;
    ?>  
     
    <?php if ($block->canKsEditQty()): ?> 
        <!-- update button start -->
        <div class="ks-sales-update-div">
            <button id="update-creditmemo-qty" class="primary" disabled="true">Update Qty's</button>
        </div>
    <?php endif; ?>     
    <!-- update button end -->  

    <section>
        <input type="hidden" name="creditmemo[do_offline]" id="creditmemo_do_offline" value="0" />
        <input type="hidden" name="creditmemo[order_id]" id="creditmemo_order_id" value="<?=$creditmemo->getOrder()->getId();?>" />
        <!-- Order tab section title start -->
        <div class="ks-tab-content-title">
            <span><?= $block->escapeHtml(__('Order Total')) ?></span>
        </div>
        <!-- Order tab section title end -->
        <div class="col-md-12">
            <div class="row">
                <div class="order-comments-history col-md-6 pl-0" id="history_form">
                    <!-- Memo tab div title start -->
                    <div class="ks-div-title mb-3">
                        <span><?= $block->escapeHtml(__('Credit Memo Comments')) ?></span>
                    </div>
                    <!-- Memo tab div title end -->

                    <div class=" ks-field-full-width">                            
                            <label class="normal"
                            for="creditmemo_comment_text">
                                <span><?= $block->escapeHtml(__('Comment Text')) ?></span>
                            </label>
                            <div>
                                <textarea id="creditmemo_comment_text"
                                name="creditmemo[comment_text]"
                                rows="3"
                                cols="5"><?= $block->escapeHtml($commentText) ?></textarea>
                            </div>                           
                    </div>
                </div>
                <div class="col-md-6 pr-0" id="creditmemo_totals">
                    <!-- Order tab div title start -->
                        <div class="ks-div-title mb-3">
                            <span><?= $block->escapeHtml(__('Refund Totals')) ?></span>
                        </div>
                    <!-- Order tab div title end -->
                    <div class="ks-sales-table">
                        <table>
                            <thead>                          
                                <tr class="subtotal">
                                    <th ><?= $block->escapeHtml(__('Subtotal')) ?></th>
                                    <td>
                                        <span class="price"><?= $block->formatValue($creditmemo->getBaseSubtotal()) ?></span>
                                        <?php if($ksShowStoreCurrency):?>
                                            <br>
                                            <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($creditmemo->getSubtotal())?></span>
                                        <?php endif;?>
                                    </td>
                                </tr>
                                <?php if($ksBaseWeeeTax >0):?>
                                    <tr class="fpt">
                                        <th ><?= $block->escapeHtml(__('FPT')) ?></th>
                                        <td>
                                            <span class="price"><?= $block->formatValue($ksBaseWeeeTax) ?></span>
                                            <?php if($ksShowStoreCurrency):?>
                                                <br>
                                                <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($ksWeeeTax)?></span>
                                            <?php endif;?>
                                        </td>
                                    </tr>
                                <?php endif;?>
                                <?php if($creditmemo->getBaseDiscountAmount()):?>
                                    <tr class="discount">
                                        <th ><?= $block->escapeHtml(__('Discount')) ?></th>
                                        <td>
                                            <span class="price"><?= $block->formatValue($creditmemo->getBaseDiscountAmount() + ($creditmemo->getBaseShippingAmount()? $creditmemo->getOrder()->getBaseShippingDiscountAmount():0 )) ?></span>
                                            <?php if($ksShowStoreCurrency):?>
                                                <br>
                                                <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($creditmemo->getDiscountAmount() + ($creditmemo->getShippingAmount()? $creditmemo->getOrder()->getShippingDiscountAmount():0 ))?></span>
                                            <?php endif;?>
                                        </td>
                                    </tr>
                                <?php endif;?>
                                <?php if($creditmemo->getBaseTaxAmount()>0):?>
                                    <tr class="discount">
                                        <th ><?= $block->escapeHtml(__('Tax')) ?></th>
                                        <td>
                                            <span class="price"><?= $block->formatValue($creditmemo->getBaseTaxAmount() - $creditmemo->getBaseShippingTaxAmount()) ?></span>
                                            <?php if($ksShowStoreCurrency):?>
                                                <br>
                                                <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($creditmemo->getTaxAmount() - $creditmemo->getShippingTaxAmount())?></span>
                                            <?php endif;?>
                                        </td>
                                    </tr>
                                <?php endif;?>
                            </thead>
                            <tfoot>
                                <?php 
                                $ksBaseTotalOrderedAmount = ($ksBaseSubtotalAmount  + $ksBaseTaxAmount) - $ksBaseDiscountAmount;
                                $ksTotalOrderedAmount = ($ksSubtotalAmount  + $ksTaxAmount) - $ksDiscountAmount;   
                                ?>
                                <tr class="grand_total">
                                    <th><?= $block->escapeHtml(__('Grand Total')) ?></th>
                                    <td>
                                        <span class="price"><?= $block->formatValue($creditmemo->getBaseGrandTotal()-$creditmemo->getBaseShippingTaxAmount()-$creditmemo->getBaseShippingAmount() + ($creditmemo->getBaseShippingAmount()? $creditmemo->getOrder()->getBaseShippingDiscountAmount():0 )) ?></span>
                                        <?php if($ksShowStoreCurrency):?>
                                            <br>
                                            <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($creditmemo->getGrandTotal() - $creditmemo->getShippingTaxAmount() - $creditmemo->getShippingAmount() + ($creditmemo->getBaseShippingAmount() ? $creditmemo->getOrder()->getShippingDiscountAmount():0 )) ?></span>
                                        <?php endif;?>
                                    </td>
                                </tr>
                                <tr>
                                    <th ><?= $block->escapeHtml(__("Total Admin's Commission")) ?></th>
                                    <td>
                                        <span class="price"><?= $block->formatValue($ksBaseTotalCommission) ?></span>
                                        <?php if($ksShowStoreCurrency):?>
                                            <br>
                                            <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($ksTotalCommission)?></span>
                                        <?php endif;?>                           
                                    </td>            
                                </tr>
                                <tr>
                                    <th ><?= $block->escapeHtml(__("Total Earning")) ?></th>
                                    <td>
                                        <span class="price"><?= $block->formatValue($ksBaseTotalEarning) ?></span>
                                        <?php if($ksShowStoreCurrency):?>
                                            <br>
                                            <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($ksTotalEarning)?></span>
                                        <?php endif;?> 
                                    </td>
                                </tr>
                            </tfoot> 
                        </table>
                    </div>

                    <div class="order-totals-actions">
                        <?php if($block->ksCheckNotesAndNotifyCreditMemo()): ?>
                        <div class="field choice field-append-comments">
                            <input id="creditmemo_notify_customer"
                            name="creditmemo[comment_customer_notify]"
                            value="1"
                            type="checkbox" disabled />
                            <label for="notify_customer">
                                <span><?= $block->escapeHtml(__('Append Comments')) ?></span>
                            </label>
                        </div>
                        <?php if ($block->canSendKsCreditmemoEmail()):?>
                        <div class="field choice field-email-copy">
                            <input id="creditmemo_send_email"
                            name="creditmemo[send_email]"
                            value="1"
                            type="checkbox" />
                            <label for="send_email">
                                <span><?= $block->escapeHtml(__('Email Copy of Credit Memo')) ?></span>
                            </label>
                        </div>
                        <?php endif; ?>
                        <?php endif; ?>
                        <div class="float-right mt-5 mb-3">
                            <button type="submit" name="submit" id="ks-submit-creditmemo" class="ks-action-btn ks-primary ks-padding-btn border-0"> <?= $block->escapeHtml('Refund Offline')?></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section> 
</div>
<!-- create credit memo page end -->

<script type="text/x-magento-init">
            {
                "*": {
                "Ksolves_MultivendorMarketplace/js/sales/creditmemo/creditmemoComment": {
                "ks_order_id": "<?php echo $block->getKsCreditmemo()->getOrderId(); ?>"
            }
        }
    }
</script>
    
