<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
 ?>
<!-- Invoice Create Action header -->
<div class="ks-page-action">
	<a href="<?= $block->getKsResetUrl();?>" class="ks-action-btn float-right ks-header-row-action"><span><?= $block->escapeHtml(__('Reset')) ?></span></a>
    <a href="<?= $block->getKsBackUrl(); ?>" class="action- scalable back ks-back"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
</div>
<!-- Invoice View Action header -->