<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

?>

<!-- Gifts section start -->
<?php if ($block->getChildHtml()) : ?>
<section class="ks-order-gift-options mb-5">

    <!-- Order tab section title start -->
    <div class="ks-tab-content-title">
        <span><?= $block->escapeHtml(__('Gift Options')) ?></span>
    </div>
    <!-- Order tab section title end -->

    <?= $block->getChildHtml() ?>

</section>
<?php endif; ?>
<!-- Gifts section end -->
