<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/** @var $block \Ksolves\Multivendor\Block\Catalog\Product\Steps\KsSummary */
?>
<div data-bind="scope: 'ks-variation-steps-wizard_ks-step4'">
    <h2 class="steps-wizard-title mb-5"><?= /* @escapeNotVerified */  __('Step 4: Summary') ?></h2>

    <div class="admin__data-grid-wrap admin__data-grid-wrap-static ks-summary-step4-section">
        <!-- ko if: gridNew().length -->
            <!-- ko template: {name: getGridTemplate(), data: {
                grid: gridNew,
                id: getGridId(),
                title: $t('New Product Review'),
                note: $t('Here are the products you\'re about to create.')
            }} --><!-- /ko -->
        <!-- /ko -->

        <!-- ko if: gridExisting().length -->
            <!-- ko template: {name: getGridTemplate(), data: {
                grid: gridExisting,
                id: getGridId(),
                title: $t('Associated Products'),
                note: $t('You created these products for this configuration.')
            }} --><!-- /ko -->
        <!-- /ko -->

        <!-- ko if: gridDeleted().length -->
            <!-- ko template: {name: getGridTemplate(), data: {
                grid: gridDeleted,
                id: getGridId(),
                title: $t('Disassociated Products'),
                note: $t('These products are not associated.')
            }} --><!-- /ko -->
        <!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "ks-variation-steps-wizard_ks-step4": {
                        "gridTemplate": "Ksolves_MultivendorMarketplace/product/variations/steps/summary-grid",
                        "component": "Ksolves_MultivendorMarketplace/js/product/variations/steps/ks-summary",
                        "appendTo": "ks-variation-steps-wizard",
                        "variationsComponent": "configurableVariations"
                    }
                }
            }
        }
    }
</script>