<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php $ks_order = $block->getKsOrder();  ?>
<?php if ($ks_order) : ?>
    <?php $_items = $block->getOrderedItems()->getAllItems(); ?>
    <table class="email-items">
        <thead>
            <tr>
                <th>
                    <?= $block->escapeHtml(__('Items')) ?>
                </th>
                <th style="text-align: center;">
                    <?= $block->escapeHtml(__('Qty')) ?>
                </th>
                <th style="text-align: right;">
                    <?= $block->escapeHtml(__('Price')) ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $ks_item) : ?>
            <?php if($block->KsIsSellerProduct($ks_item->getProductId())) : ?>
                <?php if (!$ks_item->getParentItem()) : ?>
                    <tbody>
                        <tr>
                            <td>
                                <p style="font-weight:700; margin-bottom: 5px;"><?= $block->escapeHtml(__($ks_item->getName())) ?></p></br>
                                <p><?= $block->escapeHtml("SKU: ".__($ks_item->getSku())) ?></p>
                                <!-- get ordered product attributes -->
                                <?php if ($ks_item->getProductType()=='downloadable' && $block->getKsDownloadableLinkTitle($ks_item)):?>
                                        <dl>
                                            <dt><strong><em><?= $block->escapeHtml($block->getKsDownloadableLinkTitle($ks_item)) ?></em></strong></dt>
                                            <?php foreach ($block->getKsDownloadableItemData($ks_item)->getPurchasedItems() as $link) : ?>
                                                <dd>
                                                    <?= $block->escapeHtml($link->getLinkTitle()) ?>&nbsp;
                                                    (<a href="<?= $block->escapeUrl($block->getPurchasedLinkUrl($link,$ks_item)) ?>"><?= $block->escapeHtml(__('download')) ?></a>)
                                                </dd>
                                            <?php endforeach; ?>
                                        </dl>
                                    <?php endif;?>
                            </td>
                            <td style="text-align: center;">
                                <p><?= $block->escapeHtml(__((float) $ks_item->getQtyOrdered())) ?></p>
                            </td>
                            <td style="text-align: right;">
                                <p><?= $block->formatToOrderCurrency($ks_item->getPrice(),false) ?></p>
                            </td> 
                        </tr>  
                        <?php
                        if($ks_item->getGiftMessageId()):  
                            $giftMessage = $block->getGiftMessage($ks_order->getEntityId(),$ks_item->getItemId()) ?>
                            <tr>
                                <td colspan="3" style="font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;vertical-align:top;padding:10px;border-top:0;padding-top:0">
                                <table style="border-collapse:collapse;width:100%">
                                    <tbody>
                                        <tr>
                                            <td style="font-family:'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;vertical-align:top;background-color:#fdf0d5;border:1px solid false;color:#333333;margin:0;padding:10px">
                                                <h3 style="font-weight:300;line-height:1.1;font-size:18px;margin-bottom:10px;margin-top:0">Gift Message</h3>
                                                <strong style="font-weight:700"><?= $block->escapeHtml(__('From:')) ?></strong><?= $block->escapeHtml($giftMessage->getSender()) ?> <br><strong style="font-weight:700"><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($giftMessage->getRecipient()) ?>                    <br><strong style="font-weight:700"><?= $block->escapeHtml(__('Message:')) ?></strong>
                                                <br><?= $block->escapeHtml($giftMessage->getMessage()) ?>
                                            </td>

                                        </tr>
                                    </tbody>
                                </table>
                                </td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                <?php endif; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot>
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->isMessagesAllowed('order', $ks_order, $ks_order->getStore())
        && $ks_order->getGiftMessageId()
    ) : ?>
        <?php $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->getGiftMessage($ks_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage) : ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message for this Order')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
