<!--
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
 -->
 <div id="ks_rejection_popup" style="display:none;">
    <form method="post" id="ks_reject_form">
        <textarea maxlength="200" class="form-control required-entry" name="ks_reject_message" rows="4" cols="98" placeholder="Add a message for seller"></textarea>
        <br/>
        <input type="checkbox" id="ks_notify_seller" name="ks_notify_seller" />
            <span>Notify the Seller</span>
        <input type="hidden" id="ks_id" name="id" value=""/>
        <input type="hidden" id="ks_url" name="ks_url" value=""/>
    </form>
</div>