<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/** @var $block \Ksolves\Multivendor\Block\Product\Form\Component\KsStepsWizard */
?>
<div data-role="steps-wizard-main" class="ks-modal-table-style mt-3 steps-wizard <?= /* @noEscape */ $block->getData('config/dataScope')?>" data-bind="scope: '<?= /* @escapeNotVerified */  $block->getComponentName()?>'">
    <div data-role="messages" class="messages"></div>

    <div data-role="steps-wizard-controls" class="steps-wizard-navigation ks-configurable-step-header">
        <ul class="nav-bar">
            <?php foreach ($block->getSteps() as $ksStep) { ?>
                <li data-role="collapsible" data-bind="css: { 'active': selectedStep() == '<?= /* @escapeNotVerified */  $ksStep->getComponentName() ?>'}">
                    <a href="#<?= /* @escapeNotVerified */  $ksStep->getComponentName() ?>"
                       data-bind="click: showSpecificStep">
                        <?= /* @escapeNotVerified */  $ksStep->getCaption() ?>
                    </a>
                </li>
            <?php } ?>
        </ul>
        <div class="nav-bar-outer-actions ks-configurable-step-action">
            <div class="action-wrap ks-action-wrap" data-role="closeBtn">
                <button type="button"
                        class="action-cancel action-tertiary ks-action-btn" data-bind="click: close">
                    <span><?= /* @escapeNotVerified */  __('Cancel') ?></span>
                </button>
            </div>
            <div class="action-wrap ks-action-wrap action-wrap-prev" data-role="step-wizard-prev">
                <button type="button"
                        class="action-back-step ks-action-btn ks-btn-grey mb-0"
                        data-bind="click: back, css: { 'disabled': disabled}">
                    <span><?= /* @escapeNotVerified */  __('Back') ?></span>
                </button>
            </div>
            <div class="action-wrap action-wrap-next ks-action-wrap" data-role="step-wizard-next">
                <button type="button"
                        class="action-next-step ks-action-btn ks-primary" data-bind="click: next">
                    <span><?= /* @escapeNotVerified */  __('Next') ?></span>
                </button>
            </div>
        </div>
    </div>
    <div data-role="steps-wizard-tab">
        <?php foreach ($block->getSteps() as $ksStep) { ?>
            <div data-bind="visible: selectedStep() == $element.id, css: {'no-display':false}"
                 class="content no-display" id="<?= /* @escapeNotVerified */ $ksStep->getComponentName() ?>"
                 data-role="content">
                <?= /* @escapeNotVerified */  $ksStep->getContent() ?>
            </div>
        <?php } ?>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "<?= /* @escapeNotVerified */  $block->getComponentName()?>": {
                            "component": "Ksolves_MultivendorMarketplace/js/product/lib/ks-step-wizard",
                            "initData": <?= /* @escapeNotVerified */  $this->helper("Magento\Framework\Json\Helper\Data")->jsonEncode($block->getInitData()) ?>,
                            "stepsNames": <?= /* @escapeNotVerified */  $this->helper("Magento\Framework\Json\Helper\Data")->jsonEncode($block->getStepComponents()) ?>,
                            "modalClass": "<?= /* @noEscape */ $block->getData('config/dataScope')?>"
                        }
                    }
                }
            }
    }
</script>