<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/** @var Ksolves\Multivendor\Block\Checkout\Cart\KsSellerDetails $block */
?>
<?php if($block->getKsSellerId()):?>
    <div class="ks-seller-block">
        <div><strong><?= __("Sold By");?></strong> 
            <span class="ks-seller-info">
                <a href="<?= $block->getKsSellerUrl();?>" ><?= $block->getKsSellerName();?></a>
            </span>
        </div>
    </div>
<?php endif;?>