<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/** @var $block \Ksolves\MultivendorMarketplace\Block\Adminhtml\Order\CreitMemo\Create\KsItems */
?>
<?php $invoice_item = $block->getKsSalesMemoItem($block->getKsMemoRequest()->getKsCreditmemoIncrementId(), $block->getKsOrderItemId()); ?>
<?php $_item = $block->getKsSalesMemoItem($block->getKsMemoIncId(),$block->getKsOrderItemId());?>
<?php $items = $block->getChildren($block->getKsBundleItem());
$ksShowStoreCurrency = $block->canKsShowOrderCurrencyValue(); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>
<?php
/** @var \Magento\Catalog\Helper\Data $catalogHelper */
$catalogHelper = $block->getData('ksCatalogHelper');
$ksOrderHelper = $block->getData('ksOrderHelper');
?>

<?php $_prevOptionId = '' ?>

<?php if ($block->getKsBundleItem()->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item):
    $ksOrderItem = $block->getKsOrderItem($_item->getId()); $ksMemoItem = $block->getKsSalesMemoReqItem($block->getKsMemoRequest()->getEntityId(),$_item->getId()); ?>
    <?php $attributes = $block->getSelectionAttributes($_item) ?>
    <?php if ($ksOrderItem->getParentItem()): ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
        <tr>
            <td class="col-product">
                <div class="option-label"><?= $block->escapeHtml($attributes['option_label']) ?></div>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="last">&nbsp;</td>
        </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr class="ks-bundle-item">
        <?php if (!$ksOrderItem->getParentItem()): ?>
        <td class="col-product">
            <div class="product-title"><?= $block->escapeHtml($_item->getName()) ?></div>
            <div class="product-sku-block">
                <span ><?= $block->escapeHtml(__('SKU')) ?>:</span>
                <?= /* @noEscape */ implode('<br />', $catalogHelper->splitSku($_item->getSku())) ?>
            </div>
        </td>
        <?php else: ?>
        <td class="col-product"><div class="option-value"><?= $block->getValueHtml($_item) ?></div></td>
        <?php endif; ?>
        <td class="col-price">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <span><?= $block->formatValue($ksMemoItem->getKsBasePrice() + $ksOrderItem->getBaseWeeeTaxAppliedAmount()) ?></span>
                <br>
                <?php if($ksShowStoreCurrency):?>
                        <span><?= $block->formatToOrderCurrency($ksMemoItem->getKsPrice() + $ksOrderItem->getWeeeTaxAppliedAmount())?></span>
                <?php endif;?>
                <?php if ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ksOrderItem)) : ?>
                                        
                    <span>
                        <?php foreach ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ksOrderItem) as $tax) : ?>
                            <span class="nobr"><?= $block->escapeHtml($tax['title']) ?>:<?= $block->formatValue($tax['base_amount']) ?></span>
                            <br>
                            <?php if($ksShowStoreCurrency):?>
                                <span><?= $block->formatToOrderCurrency($tax['amount'])?></span>
                            <?php endif;?>                                                  
                        <?php endforeach; ?>
                    </span>
                <?php endif; ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-qty">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <?= (float)$ksMemoItem->getKsQty() * 1 ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-subtotal">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <span><?= $block->formatValue($ksMemoItem->getKsBaseRowTotal()*$ksMemoItem->getKsQty() + ($ksOrderItem->getBaseWeeeTaxAppliedAmount() * $ksMemoItem->getKsQty())) ?></span>
                <br>
                <?php if($ksShowStoreCurrency):?>
                    <span><?= $block->formatToOrderCurrency($ksMemoItem->getKsRowTotal()*$ksMemoItem->getKsQty() + ($ksOrderItem->getWeeeTaxAppliedAmount() * $ksMemoItem->getKsQty()))?></span>
                <?php endif;?>
                <?php if ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ksOrderItem)) : ?>
                                        
                    <span>
                        <?php foreach ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($ksOrderItem) as $tax) : ?>
                            <span class="nobr"><?= $block->escapeHtml($tax['title']) ?>:<?= $block->formatValue($tax['base_amount']) ?></span>
                            <br>
                            <?php if($ksShowStoreCurrency):?>
                                <span><?= $block->formatToOrderCurrency($tax['amount'])?></span>
                            <?php endif;?>                                                  
                        <?php endforeach; ?>
                    </span>
                
                    <!-- displayFianlPrice below -->

                <?php endif; ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-tax">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <span><?= $block->formatValue($ksMemoItem->getKsBaseTaxAmount()) ?></span>
                <br>
                    <?php if($ksShowStoreCurrency):?>
                            <span><?= $block->formatToOrderCurrency($ksMemoItem->getKsTaxAmount())?></span>
                    <?php endif;?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-discount">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <span><?= $block->formatValue($ksMemoItem->getKsBaseDiscountAmount()) ?></span>
                <br>
                    <?php if($ksShowStoreCurrency):?>
                            <span><?= $block->formatToOrderCurrency($ksMemoItem->getKsDiscountAmount())?></span>
                    <?php endif;?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-total last">
            <?php if ($block->canShowPriceInfo($ksOrderItem)): ?>
                <span><?= $block->formatValue($ksMemoItem->getKsBaseRowTotal()-$ksMemoItem->getKsBaseDiscountAmount()+ ($ksOrderItem->getBaseWeeeTaxAppliedAmount() * $ksMemoItem->getKsQty()) + $ksOrderHelper->ksCalcItemBaseTaxAmt($ksOrderItem,$ksMemoItem->getKsQty())) ?></span>
                <br>
                <?php if($ksShowStoreCurrency):?>
                    <span><?= $block->formatToOrderCurrency($ksMemoItem->getKsRowTotal()-$ksMemoItem->getKsDiscountAmount() + ($ksOrderItem->getWeeeTaxAppliedAmount() * $ksMemoItem->getKsQty()) + $ksOrderHelper->ksCalcItemTaxAmt($ksOrderItem,$ksMemoItem->getKsQty()))?></span>
                <?php endif;?>
                <?php else: ?>
                 &nbsp;
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if ($_showlastRow): ?>
    <tr class="border">
        <td class="col-product">
            <?php if ($block->getOrderOptions($_item)): ?>
                <dl class="item-options">
                <?php foreach ($block->getOrderOptions($_item) as $option): ?>
                    <dt><?= $block->escapeHtml($option['label']) ?></dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?= $block->escapeHtml($option['value']) ?>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->truncateString($option['value'], 55, '', $_remainder)) ?>
                        <?php if ($_remainder):?>
                            ... <span id="<?= $block->escapeHtmlAttr($_id = 'id' . uniqid())
                            ?>"><?= $block->escapeHtml($_remainder) ?></span>
                            <?php $escapedId = /* @noEscape */ $block->escapeJs($_id);
                            $scriptString = <<<script
                                require(['prototype'], function(){
                                    $('{$escapedId}').hide();
                                    $('{$escapedId}').up().observe('mouseover', function(){\$('{$escapedId}').show();});
                                    $('{$escapedId}').up().observe('mouseout',  function(){\$('{$escapedId}').hide();});
                                });
script;
                            ?>
                            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?= $block->escapeHtml($block->getItem()->getDescription()) ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>