<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/** @var \Ksolves\MultivendorMarketplace\Block\Order\Invoice\Create\KsItems $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$creditmemo = $block->getCreditMemo();
$ksShowStoreCurrency = $block->canKsShowOrderCurrencyValue();
$ksBaseWeeeTax = 0;
$ksWeeeTax = 0;
$ks_items = $block->getCreditmemoItems();

foreach ($ks_items as $ksItem) {                                    
    $ksOrderItem = $block->getKsOrderItem($ksItem->getKsOrderItemId());
    $ksBaseWeeeTax += $ksOrderItem->getBaseWeeeTaxAppliedAmount() * $ksItem->getKsQty();
    $ksWeeeTax += $ksOrderItem->getWeeeTaxAppliedAmount() * $ksItem->getKsQty();
}

?>
<table class="data-table admin__table-secondary order-subtotal-table">
    <tfoot>
        <tr class="col-0">
            <td class="label">
                <strong><?= $block->escapeHtml(__("Grand Total")) ?></strong>
            </td>
            <td>
                <strong><span class="price"><?= $block->formatValue($creditmemo->getKsBaseGrandTotal()) ?></span></strong>
                <?php if($ksShowStoreCurrency):?>
                    <br>
                    <strong><span class="price"><?= $block->formatToOrderCurrency($creditmemo->getKsGrandTotal())?></span></strong>
                <?php endif;?>
            </td>
        </tr>
        <tr class="col-1">
             <td class="label">
                <strong><?= $block->escapeHtml(__("Total Admin's Commission")) ?></strong>
            </td>
            <td>
                <strong><span class="price"><?= $block->formatValue($creditmemo->getKsBaseTotalCommission())  ?></span></strong>
                <?php if($ksShowStoreCurrency):?>
                    <br>
                    <strong><span class="price"><?= $block->formatToOrderCurrency($creditmemo->getKsTotalCommission())?></span></strong>
                <?php endif;?>
            </td>        
        </tr>
        <tr class="col-2">
            <td class="label"><strong><?= $block->escapeHtml(__("Total Earning")) ?></strong></td>
            <td>
               <strong><span class="price"><?= $block->formatValue($creditmemo->getKsBaseTotalEarning())  ?>  </span></strong>
               <?php if($ksShowStoreCurrency):?>
                    <br>
                    <strong><span class="price"><?= $block->formatToOrderCurrency($creditmemo->getKsTotalEarning())?></span></strong>
                <?php endif;?>   
           </td>
        </tr>   
    </tfoot>
    
    <tbody>
        <tr class="col-0">
            <td class="label"><?= $block->escapeHtml(__("Subtotal")) ?></td>
            <td>
                <span><span class="price"><?= $block->formatValue($creditmemo->getKsBaseSubtotal()) ?></span></span>
                <?php if($ksShowStoreCurrency):?>
                    <br>
                    <span><span><?= $block->formatToOrderCurrency($creditmemo->getKsSubtotal())?></span></span>
                <?php endif;?>
            </td>
        </tr>
        <?php if($ksBaseWeeeTax>0):?>
            <tr class="tax">
                <th ><?= $block->escapeHtml(__('FPT')) ?></th>
                <td>
                    <span class="price"><?= $block->formatValue($ksBaseWeeeTax) ?></span>
                    <?php if($ksShowStoreCurrency):?>
                        <br>
                        <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($ksWeeeTax)?></span>
                    <?php endif;?>
                </td>
            </tr>
        <?php endif;?>
        <?php if($creditmemo->getKsBaseDiscountAmount() > 0):?>
            <tr class="col-1">
                <td class="label"><?= $block->escapeHtml(__("Discount")) ?></td>
                <td>
                    <span><span class="price"><?= $block->formatValue($creditmemo->getKsBaseDiscountAmount()) ?></span></span>
                    <?php if($ksShowStoreCurrency):?>
                        <br>
                        <span><span class="price"><?= $block->formatToOrderCurrency($creditmemo->getKsDiscountAmount())?></span></span>
                    <?php endif;?>
                </td>
            </tr>
        <?php endif;?>
        <?php if($creditmemo->getKsBaseTaxAmount()>0):?>
            <tr class="tax">
                <th ><?= $block->escapeHtml(__('Tax')) ?></th>
                <td>
                    <span class="price"><?= $block->formatValue($creditmemo->getKsBaseTaxAmount()) ?></span>
                    <?php if($ksShowStoreCurrency):?>
                        <br>
                        <span class="ks-sales-currency-rate"><?= $block->formatToOrderCurrency($creditmemo->getKsTaxAmount())?></span>
                    <?php endif;?>
                </td>
            </tr>
        <?php endif;?>
        <?php if($creditmemo->getKsBaseShippingAmount() > 0):?>
            <tr class="col-2">
                <td class="label"><?= $block->escapeHtml(__("Shipping &amp; Handling")) ?></td>
                <td>
                    <span><span class="price"><?= $block->formatValue($creditmemo->getKsBaseShippingAmount()) ?></span></span>
                    <?php if($ksShowStoreCurrency):?>
                        <br>
                        <span><span class="price"><?= $block->formatToOrderCurrency($creditmemo->getKsShippingAmount())?></span></span>
                    <?php endif;?>
                </td>
            </tr>
        <?php endif;?>
        <tr class="col-3">
            <td class="label"> <?= $block->escapeHtml(__('Adjustment Refund')) ?></td>
            <td>
                <span class="price"><?= $block->formatValue($creditmemo->getKsBaseAdjustmentPositive()) ?></span>
                <?php if($ksShowStoreCurrency):?>
                    <br>
                    <span class="price"><span><?= $block->formatToOrderCurrency($creditmemo->getKsAdjustmentPositive())?></span></span>
                <?php endif;?>
            </td>
        </tr>
        <tr class="col-4">
           <td class="label"><?= $block->escapeHtml(__('Adjustment Fee')) ?></td>
            <td>
                <span class="price"><?= $block->formatValue($creditmemo->getKsBaseAdjustmentNegative()) ?></span>
                <?php if($ksShowStoreCurrency):?>
                    <br>
                    <span class="price"><?= $block->formatToOrderCurrency($creditmemo->getKsAdjustmentNegative())?></span>
                <?php endif;?>
            </td>
        </tr>
    </tbody>
</table>
