<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
?>
<?php $order= $block->getKsOrder();?>

<!-- Order increment id start --> 
<div class="ks-main-page-title">
    <span><?= "#".$block->escapeHtml(__($order->getIncrementId())) ?></span>
</div>
<!-- Order increment id end --> 