<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
?>
<?php
    $ksAdminFrontName = $this->helper('Magento\Backend\Helper\Data')->getAreaFrontName();
    $ksAdminBaseUrl = $block->getBaseUrl() . $ksAdminFrontName . '/';
;
?>
<script type="text/javascript">
    require([
        'mage/url'
    ], function(url) {
        return url.setBaseUrl("<?= $ksAdminBaseUrl;?>");
    });
</script>
