<!--
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
 -->
<div id="ks_assign_product_details" style="display:none;">
    <form method="post" class="ks_assign_product_form">
        <input type="hidden" class="ks_assign_product_seller_id">
        <input type="hidden" class="ks_assign_product_id">
        <div class="ks_product_to_be_assigned"></div>
    </form>
</div>
