<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/** @var $block \Ksolves\MultivendorMarketplace\Block\Product\Form\Tabs\Variations\Config\KsMatrix */
?>
<?php
$ksProductMatrix = $block->getKsProductMatrix();
$ksAttributes = $block->getKsProductAttributes();
$currencySymbol = $block->getKsCurrentCurrency();
$ksIsEdit = $block->getKsIsProductEdit();

/** @var \Magento\Framework\Json\Helper\Data $jsonHelper */
$ksJsonHelper = $this->helper('Magento\Framework\Json\Helper\Data');
    
?>
<div class="entry-edit form-inline" id="<?= $block->escapeHtmlAttr($block->getId()) ?>" data-panel="product-variations">
    <div class="product-create-configuration">
        <div class="product-create-configuration-info">
            <div class="note" data-role="product-create-configuration-info">
                <?= $block->escapeHtml(__('Configurable products allow customers to choose options (Ex: shirt color). You need to create a simple product for each configuration (Ex: a product for each color).'));?>
            </div>
        </div>
    </div>
    <div class="fieldset">
        <input type="hidden" name="affect_configurable_product_attributes" value="1" />
    </div>
</div>
<div id="product-variations-matrix" data-role="product-variations-matrix">
    <div data-bind="scope: 'configurableVariations'">
        <h3 class="hidden" data-bind="css: {hidden: !showVariations() }" class="title">
            <?= __('Current Variations'); ?>
        </h3>

        <script data-template-for="variation-image" type="text/x-magento-template">
            <img src="<%= data.url %>" class="variation" data-role="image"/>
        </script>
        <!-- ko if: showVariations() -->
            <div class="field hidden" data-bind="css: {hidden: !showVariations() }">
                <div data-role="configurable-attributes-container">
                    <!-- ko foreach: {data: attributes, as: 'attribute'} -->
                        <div data-role="attribute-info">
                            <input name="attributes[]" data-bind="value: attribute.id, attr:{id: 'configurable_attribute_' + attribute.id}" type="hidden"/>
                            <input data-bind="value: attribute.id, attr: {name: $parent.getAttributeRowName(attribute, 'attribute_id')}" type="hidden"/>
                            <input data-bind="value: attribute.code, attr: {name: $parent.getAttributeRowName(attribute, 'code')}" type="hidden"/>
                            <input data-bind="value: attribute.label, attr: {name: $parent.getAttributeRowName(attribute, 'label')}" type="hidden"/>
                            <input data-bind="value: $index(), attr: {name: $parent.getAttributeRowName(attribute, 'position')}" type="hidden"/>
                            <!-- ko foreach: {data: attribute.chosen, as: 'option'} -->
                                <div data-role="option-info">
                                    <input value="1" data-bind="attr: {name: $parents[1].getOptionRowName(attribute, option, 'include')}" type="hidden"/>
                                    <input data-bind="value: option.value, attr: {name: $parents[1].getOptionRowName(attribute, option, 'value_index')}" type="hidden"/>
                                </div>
                            <!-- /ko -->
                        </div>
                    <!-- /ko -->
                </div>
               
                <div class="admin__data-grid-wrap  grid-container admin__data-grid-wrap-static">
                    <?= $block->getLayout()
                        ->createBlock('Magento\Framework\View\Element\Template')
                        ->setTemplate('Ksolves_MultivendorMarketplace::product/form/tabs/link-item/ks-custom-paging.phtml')
                        ->toHtml();?>

                    <table class="data-grid">
                        <thead>
                            <tr>
                                <th class="data-grid-th data-grid-thumbnail-cell col-image" data-column="image">
                                    <?=  __('Image'); ?>
                                </th>
                                <th class="data-grid-th col-name" data-column="name">
                                    <?=  __('Name'); ?>
                                </th>
                                <th class="data-grid-th col-sku" data-column="sku">
                                    <?=  __('SKU'); ?>
                                </th>
                                <th class="data-grid-th col-price" data-column="price">
                                    <?=  __('Price'); ?>
                                </th>
                                <th class="data-grid-th col-qty" data-column="qty">
                                    <?=  __('Quantity'); ?>
                                </th>
                                </th>
                                <th class="data-grid-th col-weight" data-column="weight">
                                    <?=  __('Weight'); ?>
                                </th>
                                <th class="data-grid-th col-status" data-column="status">
                                    <?=  __('Status'); ?>
                                </th>
                                <th class="data-grid-th col-attr" data-column="attributes">
                                    <?=  __('Attributes'); ?>
                                <th class="data-grid-th col-stage" data-column="stage">
                                    <?=  __('Condition'); ?>
                                </th>
                                <th class="data-grid-th">
                                    <?=  __('Actions'); ?>
                                </th>
                            </tr>
                        </thead>
                        <tbody data-bind="foreach: {data: productMatrix, as: 'variation'}, afterRender: renderedPager">
                            <tr class="ks-gridrow" data-role="row" data-bind="css: { _disabled: !variation.status, even: $index() % 2 },
                                attr: { 'data-row-number': $index() }">
                                <td class="col-image" data-column="image">
                                    <div class="actions split actions-image-uploader">
                                        <div class="action-upload action split" data-action="upload-image">
                                            <!-- ko if: $parent.isShowPreviewImage(variation) -->
                                                <img data-bind='attr: {src: variation.images.preview}' class="variation"
                                                     data-role="image"/>
                                            <!-- /ko -->
                                            <!-- ko if: variation.editable-->
                                                <input type="hidden" data-bind="
                                                    attr: {id: $parent.getRowId(variation, 'image'),
                                                    name: $parent.getVariationRowName(variation, 'image')}"/>
                                                <span><?=  __('Upload Image'); ?></span>
                                                <input name="image" type="file"
                                                       data-url="<?= $block->getUrl('multivendor/product_gallery/upload', ['_secure' => $this->getRequest()->isSecure()]); ?>"
                                                       title="<?= __('Upload image'); ?>"/>
                                            <!-- /ko -->
                                        </div>
                                        <!-- ko if: variation.editable -->
                                            <!-- ko if: variation.images.file -->
                                                <span data-bind="html: $parent.generateImageGallery(variation)"
                                                      data-block="variation-images"></span>
                                            <!-- /ko -->
                                        <!-- /ko -->

                                        <!-- ko if: variation.editable -->
                                            <!-- ko if: variation.images.file -->
                                                <div class="dropdown show">
                                                    <button type="button" class="ks-image-dropdown dropdown-toggle" data-toggle="dropdown">
                                                        <span><?=  __('Select'); ?></span>
                                                    </button>
                                                    <ul class="dropdown-menu">
                                                        <li>
                                                            <a class="item" data-action="no-image"><?= __('No Image'); ?></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            <!-- /ko -->
                                        <!-- /ko -->
                                    </div>
                                </td>
                                <td class="col-name" data-column="name">
                                    <?php if ($ksIsEdit) : ?>
                                        <a target="_blank" data-bind="text: variation.name,
                                            attr: {href: variation.productUrl}">
                                        </a>
                                    <?php else: ?>
                                        <input type="text" class="required-entry" data-bind="
                                            attr: {id: $parent.getRowId(variation, 'name'),
                                            name: $parent.getVariationRowName(variation, 'name'),
                                             value: variation.name}" readonly="true" />
                                        <input type="hidden" data-bind="
                                            attr: {id: $parent.getRowId(variation, 'configurable_attribute'),
                                            name: $parent.getVariationRowName(variation, 'configurable_attribute'),
                                            value: variation.attribute}"/>
                                    <?php endif; ?>                              
                                </td>
                                <td class="col-sku" data-column="sku">
                                    <input type="text" class="required-entry"
                                           data-bind="attr: {id: $parent.getRowId(variation, 'sku'),
                                            name: $parent.getVariationRowName(variation, 'sku'),
                                            value: variation.sku}"/>
                                </td>
                                <td class="col-price" data-column="price">
                                    <div class="addon configure-table-dollor ks-dollor-sign">
                                        <span data-bind="text: $parent.getCurrencySymbol()"></span>
                                        <input type="text"
                                               id=""
                                               class="required-entry validate-zero-or-greater dollor-input-style"
                                               data-bind="attr: {id: $parent.getRowId(variation, 'price'),
                                                name: $parent.getVariationRowName(variation, 'price'),
                                                 value: variation.price}"/>
                                    </div>
                                </td>
                                <?php if ($ksIsEdit) : ?>
                                    <td class="col-qty" data-column="qty">
                                        <input type="text"
                                               class="validate-zero-or-greater"
                                               data-bind="attr: {id: $parent.getRowId(variation, 'qty'),
                                                name: $parent.getVariationRowName(variation, 'qty'),
                                                value: variation.quantity}"/>
                                    </td>
                                <?php else: ?>
                                    <td class="col-qty" data-column="qty">
                                        <input type="text"
                                           class="validate-zero-or-greater"
                                           data-bind="attr: {id: $parent.getRowId(variation, 'qty'),
                                            name: $parent.getVariationRowName(variation, 'qty')}"/>
                                    </td>
                                <?php endif; ?>
                                <td class="col-weight" data-column="weight">
                                    <input value="1" type="hidden" value="1" data-bind="
                                        attr: {id: $parent.getRowId(variation, 'canEdit'),
                                        name: $parent.getVariationRowName(variation, 'canEdit')}"/>

                                    <input type="text" class="validate-zero-or-greater"
                                           data-bind="
                                               attr: {id: $parent.getRowId(variation, 'weight'),
                                               name: $parent.getVariationRowName(variation, 'weight'),
                                               value: variation.weight}"/>
                                </td>
                                <td class="col-attr" data-column="status" >
                                    <!-- ko ifnot: variation.editable -->
                                        <input type="hidden" data-bind="
                                            attr: {id: $parent.getRowId(variation, 'id'),
                                            name: $parent.getVariationRowName(variation, 'id'),
                                            value: variation.productId}"/>

                                        <input value="0" type="hidden" data-bind="
                                            attr: {id: $parent.getRowId(variation, 'newProduct'),
                                            name: $parent.getVariationRowName(variation, 'newProduct')}"/>
                                    <!-- /ko -->

                                    <input type="hidden" data-bind="
                                    attr: {id: $parent.getRowId(variation, 'status'),
                                    name: $parent.getVariationRowName(variation, 'status'),
                                    value: variation.status == 1 ? 1 : 2 }"/>

                                    <input type="hidden" data-bind="
                                            attr: {id: $parent.getRowId(variation, 'was_changed'),
                                            name: $parent.getVariationRowName(variation, 'was_changed'),
                                            value: variation.was_changed}"/>

                                    <span data-bind="text: variation.status == 1 ? $t('Enabled') : $t('Disabled')"></span>
                                </td>
                                <td class="col-attr" data-column="attributes" >
                                    <!-- ko foreach: variation.options -->
                                        <span data-bind="text: attribute_label"></span>:
                                        <span data-bind="text: label"></span>
                                    <!-- /ko -->
                                </td>
                                <td class="col-condition" data-column="stage">
                                    <select data-bind="attr: {id: $parent.getRowId(variation, 'stage'),
                                                             name:$parent.getVariationRowName(variation, 'stage'),}">
                                        <option value="1" data-bind="attr: {
                                            selected:variation.stage == 1 ? true : false }"
                                            >New</option>
                                        <option value="0" data-bind="attr: {
                                            selected:variation.stage == 0 ? true : false }">Used</option>
                                    </select>
                                </td>
                                <td class="data-grid-actions-cell">
                                    <input type="hidden" name="associated_product_ids[]" data-bind="value: variation.productId" data-column="entity_id"/>
                                    <div class="action-select-wrap" data-bind="
                                            css : {
                                                '_active' : $parent.opened() === $index()
                                            },
                                            outerClick: $parent.closeList.bind($parent, $index)"
                                    >
                                        <button class="action-select" data-bind="click: $parent.toggleList.bind($parent, $index())">
                                            <span data-bind="i18n: 'Select'"></span>
                                        </button>
                                        <ul class="action-menu _active" data-bind="css: {'_active': $parent.opened() === $index()}">
                                            <li>
                                                <a class="action-menu-item" data-bind="
                                                    text: variation.status == 1 ? $t('Disable Product') : $t('Enable Product'),
                                                    click: $parent.toggleProduct.bind($parent, $index())">
                                                </a>
                                            </li>
                                            <li>
                                                <a class="action-menu-item" data-bind="click: $parent.removeProduct.bind($parent, $index())">
                                                    <?=  __('Remove Product');?>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        <!-- /ko -->
    </div>
    <div data-role="step-wizard-dialog"
         data-mage-init='{"Magento_Ui/js/modal/modal":{"type":"slide","title":"<?=
            $block->escapeJs(__('Create Product Configurations')) ?>",
         "buttons":[]}}' class="no-display">
            <?= /* @noEscape */ $block->getKsVariationStepsWizard([
                'attributes' => $ksAttributes,
                'configurations' => $ksProductMatrix
            ]);
?>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "configurableVariations": {
                        "component": "Ksolves_MultivendorMarketplace/js/product/variations/ks-variations",
                        "variations": <?= /* @noEscape */ $ksJsonHelper->jsonEncode($ksProductMatrix) ?>,
                        "productAttributes": <?= /* @noEscape */ $ksJsonHelper->jsonEncode($ksAttributes) ?>,
                        "productUrl": "<?= /* @noEscape */ $block->getUrl('multivendor/pricecomparison/editproduct', ['id' => 'productid', 'parent_id' => $block->getRequest()->getParam('parent_id') ]) ?>",
                        "currencySymbol": "<?= /* @noEscape */ $currencySymbol ?>",
                        "configurableProductGrid": "configurableProductGrid"
                    }
                }
            }
        }
    }
</script>