<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/** @var \Ksolves\MultivendorMarketplace\Block\Order\Shipment\View\CommentsHistory */
$shipment = $block->getKsShipment();
$ksComments = $block->getKsComments();
?>

<!-- order total section start -->
<?php if($shipment->getKsApprovalStatus()!=2):?>
    <form class="entry-edit form-inline" id="shipment_history_section">
<?php endif;?>
    <div class="shipment_history_block w-100" id="shipment_history_block">
        <div><input type="hidden" name="id" value="<?= $shipment->getId()?>"></div>
        <div id="comments_block" class="edit-order-comments">
            <div class=" ks-field-full-width">
                <label 
                for="history_comment"><?= $block->escapeHtml(__('Comment Text')) ?></label>
                <div>
                    <textarea name="comment[comment]"
                    class="ks-control-feild"
                    rows="3"
                    cols="5"
                    id="history_comment"></textarea>
                </div>
            </div>
        </div>
        <?php if($block->ksCheckNotesAndNotifyShipment()): ?>
        <div class="order-history-comments-options mt-4">
            <?php if($shipment->getKsApprovalStatus()!=2):?>
                <?php if ($block->canSendCommentEmail()): ?>
                    <div>
                        <input name="comment[is_customer_notified]"
                        type="checkbox"
                        id="history_notify"
                        value="1" />
                        <span for="history_notify"><?= $block->escapeHtml(__('Notify Customer by Email')) ?></span>
                    </div>
                <?php endif; ?>
                <div>
                    <input name="comment[is_visible_on_front]"
                    type="checkbox"
                    id="history_visible"
                    value="1" />
                    <span for="history_visible"> <?= $block->escapeHtml(__('Visible on Storefront')) ?></span>
                </div>
            <?php else:?>
                <?php if($block->ksCheckNotesAndNotifyShipment()): ?>
                    <div class="field-append">
                        <input id="notify_customer" name="shipment[comment_customer_notify]" value="1" type="checkbox" />
                        <label for="notify_customer">
                            <?= $block->escapeHtml(__('Append Comments')) ?>
                        </label>
                    </div>
                    <div class="field-email">
                        <input id="send_email" name="shipment[send_email]" value="1" type="checkbox" />
                        <label for="send_email">
                            <?= $block->escapeHtml(__('Email Copy of Shipment')) ?>
                        </label>
                    </div>
                <?php endif; ?>
            <?php endif;?>    
        </div>
    <?php endif; ?>
        <?php if($shipment->getKsApprovalStatus()!=2):?>
            <div class="order-history-comments-actions mt-4">
                <button class="ks-action-btn ks-secondry" id="comment-shipment"><?= $block->escapeHtml(__('Submit Comment')) ?></button>
            </div>
        <?php else:?>
            <div class="order-history-comments-actions mt-4">
                <input type="submit" name="submit" class="ks-action-btn ks-primary ks-padding-btn border-0" value="<?= $block->escapeHtml('Submit Shipment')?>">
            </div>
        <?php endif; ?>
       <?php  if($shipment->getKsApprovalStatus()): ?>
        <ul class="ks-order-status-list mt-5">
            <?php foreach ($ksComments as  $ksComment): ?>
                <li>
                    <span class="note-list-date pr-3">
                        <?= /* @noEscape */ $block->formatDate($ksComment->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?>
                    </span>
                    <span class="note-list-time pr-3">
                        <?= /* @noEscape */ $block->formatTime($ksComment->getCreatedAt(), \IntlDateFormatter::MEDIUM) ?>
                    </span>
                    <span class="note-list-customer pl-3">
                        <?= $block->escapeHtml(__('Customer')) ?>
                        <?php if ($ksComment->getIsCustomerNotified()): ?>
                        <span class="font-weight-bold note-list-customer-notified"><?= $block->escapeHtml(__('Notified')) ?></span>
                        <?php else: ?>
                            <span class="note-list-customer-not-notified font-weight-bold">
                                <?= $block->escapeHtml(__('Not Notified')) ?>
                            </span>
                        <?php endif; ?>
                    </span>
                    <div class="note-list-comment font-12">
                        <?= $block->escapeHtml($ksComment->getComment(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
            <?php else:?>
                <?php if($ksComments->getKsCustomerNote()):?>
                    <ul class="ks-order-status-list mt-5">                                                          
                        <li>
                            <span class="note-list-date pr-3">
                                <?= /* @noEscape */ $block->formatDate($ksComments->getKsCreatedAt(), \IntlDateFormatter::MEDIUM) ?>
                            </span>
                            <span class="note-list-time pr-3">
                                <?= /* @noEscape */ $block->formatTime($ksComments->getKsCreatedAt(), \IntlDateFormatter::MEDIUM) ?>
                            </span>
                            <span class="note-list-customer pl-3">
                            <?= $block->escapeHtml(__('Customer')) ?>
                            <?php if ($ksComments->getKsCustomerNoteNotify()): ?>
                                <span class="font-weight-bold note-list-customer-notified"><?= $block->escapeHtml(__('Notified')) ?></span>
                                <?php else: ?>
                                    <span class="note-list-customer-not-notified font-weight-bold">
                                        <?= $block->escapeHtml(__('Not Notified')) ?>
                                    </span>
                                <?php endif; ?>
                            </span>
                            <div class="note-list-comment font-12">
                                <?= $block->escapeHtml($ksComments->getKsCustomerNote(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?>
                            </div>
                        </li>                           
                    </ul>
                <?php endif;?>       
            <?php endif; ?>
    </div>
<?php if($shipment->getKsApprovalStatus()!=2):?>
    </form>
<?php endif;?>
<!-- order total section end -->

<script type="text/x-magento-init">
        {
            "*": {
            "Ksolves_MultivendorMarketplace/js/sales/shipment/shipmentComment": {
            "shipment_id": "<?php echo $shipment->getEntityId(); ?>"
        }
    }
}
</script>
