<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
/**
 * @var \Ksolves\MultivendorMarketplace\Block\Order\Shipment\View\KsForm $block
 */

$shipment=$block->getKsShipment();
?>

<!-- Shipment increment id start --> 
    <div class="ks-main-page-title">
        <span><?= "#".$block->escapeHtml(__($shipment->getKsShipmentIncrementId())) ?></span>
    </div>
<!-- Shipment increment id start -->