<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/** @var $block \Ksolves\MultivendorMarketplace\Block\Order\Create\Invoice\KsItems */
?>
<?php if($block->getKsInvoiceRequest()->getKsApprovalStatus()!=\Ksolves\MultivendorMarketplace\Model\KsSalesInvoice::KS_STATUS_APPROVED):?>
    <?= $block->getLayout()->createBlock('Ksolves\MultivendorMarketplace\Block\Adminhtml\Order\Invoice\View\Items')->setKsOrderItemId($block->getKsOrderItemId())->setKsBundleItem($block->getKsBundleItem())->setKsInvoiceRequest($block->getKsInvoiceRequest())->setTemplate('Ksolves_MultivendorMarketplace::order/invoice/view/bundle/request-items-renderer.phtml')->toHtml(); ?>
<?php else:?>
<?php $invoice_item = $block->getKsSalesInvoiceItem($block->getKsInvoiceIncId(),$block->getKsOrderItemId());$ksShowStoreCurrency = $block->canKsShowOrderCurrencyValue();
 ?>
<?php $items = $block->getChildren($invoice_item); ?>
<?php $_count = count($items) ?>
<?php $_index = 0; ?>
<?php
/** @var \Magento\Catalog\Helper\Data $catalogHelper */
$catalogHelper = $block->getData('ksCatalogHelper');
$ksOrderHelper = $block->getData('ksOrderHelper');
?>
<?php if ($invoice_item->getOrderItem()->getOrder()->getOrderOptions() || $invoice_item->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php $_prevOptionId = '' ?>
<?php foreach ($items as $_item): ?>
    <?php if ($_item->getOrderItem()->getParentItem()): ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
        <tr>
            <td class="col-product">
                <div class="option-label"><?= $block->escapeHtml($attributes['option_label']) ?></div>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="last">&nbsp;</td>
        </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr class="ks-bundle-item">
        <?php if (!$_item->getOrderItem()->getParentItem()): ?>
        <td class="col-product">
            <div class="product-title"><?= $block->escapeHtml($_item->getName()) ?></div>
            <div class="product-sku-block">
                <span><?= $block->escapeHtml(__('SKU')) ?>:</span>
                <?= /* @noEscape */ implode('<br />', $catalogHelper->splitSku($_item->getSku())) ?>
            </div>
        <?php else: ?>
        <td class="col-product">
            <div class="option-value"><?= $block->getValueHtml($_item) ?></div>
        </td>
        <?php endif; ?>
        <td class="col-price">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <span><?= $block->formatValue($_item->getBasePrice() + $_item->getBaseWeeeTaxAppliedAmount()) ?></span>
                <br>
                <?php if($ksShowStoreCurrency):?>
                        <span><?= $block->formatToOrderCurrency($_item->getPrice() + $_item->getWeeeTaxAppliedAmount())?></span>
                <?php endif;?>
                <?php if ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($_item)) : ?>
                                        
                    <span>
                        <?php foreach ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($_item) as $tax) : ?>
                            <span class="nobr"><?= $block->escapeHtml($tax['title']) ?>:<?= $block->formatValue($tax['base_amount']) ?></span>
                            <br>
                            <?php if($ksShowStoreCurrency):?>
                                <span><?= $block->formatToOrderCurrency($tax['amount'])?></span>
                            <?php endif;?>                                                  
                        <?php endforeach; ?>
                    </span>

                <?php endif; ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-qty">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= (float)$_item->getQty() * 1 ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-subtotal">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <span><?= $block->formatValue($_item->getBasePrice()*$_item->getQty() + ($_item->getOrderItem()->getBaseWeeeTaxAppliedAmount() * $_item->getQty())) ?></span>
                <br>
                <?php if($ksShowStoreCurrency):?>
                    <span><?= $block->formatToOrderCurrency($_item->getPrice()*$_item->getQty() + ($_item->getOrderItem()->getWeeeTaxAppliedAmount() * $_item->getQty()))?></span>
                <?php endif;?>
                <?php if ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($_item)) : ?>
                                        
                    <span>
                        <?php foreach ($this->helper(\Magento\Weee\Helper\Data::class)->getApplied($_item) as $tax) : ?>
                            <span class="nobr"><?= $block->escapeHtml($tax['title']) ?>:<?= $block->formatValue($tax['base_amount'] * $_item->getQty()) ?></span>
                            <br>
                            <?php if($ksShowStoreCurrency):?>
                                <span><?= $block->formatToOrderCurrency($tax['amount'] * $_item->getQty())?></span>
                            <?php endif;?>                                                  
                        <?php endforeach; ?>
                    </span>

                <?php endif; ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-tax">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <span><?= $block->formatValue($_item->getBaseTaxAmount()) ?></span>
                <br>
                    <?php if($ksShowStoreCurrency):?>
                            <span><?= $block->formatToOrderCurrency($_item->getTaxAmount())?></span>
                    <?php endif;?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-discount">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <span><?= $block->formatValue($_item->getBaseDiscountAmount()) ?></span>
                    <br>
                        <?php if($ksShowStoreCurrency):?>
                                <span><?= $block->formatToOrderCurrency($_item->getDiscountAmount())?></span>
                        <?php endif;?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-total last">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <span><?= $block->formatValue($_item->getBaseRowTotal()-$_item->getBaseDiscountAmount() + ($_item->getOrderItem()->getBaseWeeeTaxAppliedAmount() * $_item->getQty()) + $ksOrderHelper->ksCalcItemBaseTaxAmt($_item->getOrderItem(),$_item->getQty())) ?></span>
                    <br>
                    <?php if($ksShowStoreCurrency):?>
                        <span><?= $block->formatToOrderCurrency($_item->getRowTotal()-$_item->getDiscountAmount() + $ksOrderHelper->ksCalcItemTaxAmt($_item->getOrderItem(),$_item->getQty()) + ($_item->getOrderItem()->getWeeeTaxAppliedAmount() * $_item->getQty()))?></span>
                    <?php endif;?>
                <?php else: ?>
                 &nbsp;
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if ($_showlastRow): ?>
    <tr class="border">
        <td class="col-product">
            <?php if ($block->getOrderOptions($invoice_item)): ?>
                <dl class="item-options">
                <?php foreach ($block->getOrderOptions($invoice_item) as $option): ?>
                    <dt><?= $block->escapeHtml($option['label']) ?></dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?= $block->escapeHtml($option['value']) ?>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->truncateString($option['value'], 55, '', $_remainder)) ?>
                        <?php if ($_remainder):?>
                            ... <span id="<?= $block->escapeHtmlAttr($_id = 'id' . uniqid())
                            ?>"><?= $block->escapeHtml($_remainder) ?></span>
                            <?php $escapedId = /* @noEscape */ $block->escapeJs($_id);
                            $scriptString = <<<script
                                require(['prototype'], function(){
                                    $('{$escapedId}').hide();
                                    $('{$escapedId}').up().observe('mouseover', function(){\$('{$escapedId}').show();});
                                    $('{$escapedId}').up().observe('mouseout',  function(){\$('{$escapedId}').hide();});
                                });
script;
                            ?>
                            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?= $block->escapeHtml($block->getItem()->getDescription()) ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>
<?php endif;?>