<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

/**
 * Seller Profile Products template
 *
 * @var $block \Ksolves\MultivendorMarketplace\Block\SellerProfile\KsRecentlyProducts
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $title = __('');
    $items = $block->getProductCollection()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>
<?php if ($exist) :?>
    <div class="widget block-new-products <?= /* @noEscape */ $mode ?>">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?= $block->escapeHtml($title) ?></strong>
        </div>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products wrapper products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="products list items product-items <?= /* @noEscape */ $type ?> ks-best-products">
                    <?php $count = 1; ?>  
                    <?php foreach ($items as $_item) :?>  
                    <li class="item product product-item ks-best-products-<?= $count ?>">
                        <div class="product-item-info"> 
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product-item-photo product photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details product details">
                                <strong class="product-item-name product name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php if ($templateType) :?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <script>
                                        require(["jquery"
                                                ], 
                                                function ($) {       
                                                $('.ks-best-products-<?= $count ?> .rating-summary .rating-result > span').each(function(){
                                                    var ksPercentage = $(this).parent().attr("title");
                                                    $(this).css("width",ksPercentage);
                                                    return false;
                                                });
                                        });
                                    </script>
                                <?php endif; ?>
                                <?= $block->getProductPriceHtml($_item, $type); ?>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <?php if ($showWishlist || $showCompare || $showCart) :?>
                                        <div class="actions-primary">
                                            <?php if ($showCart) :?>
                                                <div class="">
                                                    <?php if ($_item->isSaleable()) :?>
                                                        <?php if (!$_item->getTypeInstance()->isPossibleBuyFromList($_item)) :?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                                    type="button"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php else :?>
                                                            <?php
                                                                $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
                                                                $postData = $postDataHelper->getPostData(
                                                                    $block->escapeUrl($block->getAddToCartUrl($_item)),
                                                                    ['product' => (int) $_item->getEntityId()]
                                                                )
                                                            ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?= /* @noEscape */ $postData ?>'
                                                                    type="button"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else :?>
                                                        <?php if ($_item->getIsSalable()) :?>
                                                            <div class="stock available">
                                                                <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                            </div>
                                                        <?php else :?>
                                                            <div class="stock unavailable">
                                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        <?php endif; ?>

                                        <?php if ($showWishlist || $showCompare) :?>
                                        <div class="actions-secondary ks_heart" data-role="add-to-links">
                                            <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) :?>
                                                <a href="#"
                                                    data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                                    class="action towishlist"
                                                    data-action="add-to-wishlist"
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare) :?>
                                                <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                                                <a href="#" class="action tocompare ks-tocompare"
                                                    data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                     </li>
                     <?php $count++; ?> 
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php else: ?>
    <div class="message info empty ks-margin-bottom-2">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php endif;?>
