<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

$ksStores = $block->getStoresSortedBySortOrder();
?>
<fieldset class="admin__fieldset fieldset ks-manage-options-panel mt-5 ks-attribute-hide-field">
    <div class="ks-form-collapsible-block">
        <div class="ks-fieldset-wrapper-title">
            <div class="ks-form-collapsible-title ks-after-none ks-cursor-inherit">
            <span><?= $block->escapeHtml(__('Manage Options (Values of Your Attribute)')) ?></span>
            </div>
        </div>
    </div>
    <div class="admin__control-table-wrapper ks-advance-table" id="manage-options-panel" data-index="attribute_options_select_container">
        <table class="admin__control-table ks-tiers_table table" data-index="attribute_options_select">
            <thead>
                <tr id="attribute-options-table">
                    <th class="col-draggable ks-draggable-handle"></th>
                    <th class="col-default control-table-actions-th">
                        <span><?= $block->escapeHtml(__('Is Default')) ?></span>
                    </th>
                    <?php
                    foreach ($ksStores as $ksStore):?>
                        <th<?php if ($ksStore->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID):?> class="_required"<?php endif; ?>>
                        <?php  if ($ksStore->getName() == 'Admin'):?>
                            <span><?= $block->escapeHtml(__('Default')) ?></span>
                        <?php else:?>
                            <span><?= $block->escapeHtml(__($ksStore->getName())) ?></span>
                        <?php endif;?>
                    </th>
                <?php endforeach;
                    $ksStoreTotal = count($ksStores) + 3;
                    ?>
                <th class="col-delete ks-col-delete">&nbsp;</th>
            </tr>
        </thead>
        <tbody data-role="options-container" class="ignore-validate"></tbody>
        <tfoot>
            <tr>
                <th colspan="<?= (int) $ksStoreTotal ?>" class="col-actions-add ks-col-actions-add">
                    <button id="add_new_option_button" data-action="add_new_row"
                    title="<?= $block->escapeHtml(__('Add Option')) ?>"
                    type="button" class="action- scalable add primary">
                    <span><?= $block->escapeHtml(__('Add Option')) ?></span>
                </button>

            </th>
        </tr>
    </tfoot>
</table>
<input type="hidden" id="option-count-check" value="" />
</div>
<?php
    $ksValues = [];
foreach ($block->getOptionValues() as $ksValue) {
    $ksValue = $ksValue->getData();
    $ksValues[] = is_array($ksValue) ? array_map(function ($str) {
        return htmlspecialchars_decode($str, ENT_QUOTES);
    }, $ksValue) : $ksValue;
}
$ksValues = $ksValues ? $ksValues : $block->getKsOptions();
?>
<script id="row-template" type="text/x-magento-template">
        <tr <% if (data.rowClasses) { %>class="<%- data.rowClasses %>"<% } %>>
            <td class="col-draggable ks-draggable-handle">
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()):?>
                    <div data-role="draggable-handle" class="draggable-handle"
                         title="<?= $block->escapeHtml(__('Sort Option')) ?>">
                    </div>
                <?php endif; ?>
                <input data-role="order" type="hidden" name="option[order][<%- data.id %>]"  value="<%- data.sort_order %>" <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()):?> disabled="disabled"<?php endif; ?>/>
            </td>
            <td class="col-default control-table-actions-cell">
                <input class="input-radio" type="<%- data.intype %>" name="default[]" value="<%- data.id %>" <%- data.checked %><?php if ($block->getReadOnly()):?>disabled="disabled"<?php endif;?>/>
            </td>
            <?php foreach ($ksStores as $ksStore):?>
            <td class="col-<%- data.id %>"><input name="option[value][<%- data.id %>][<?= (int) $ksStore->getId() ?>]" value="<%- data.store<?= /* @noEscape */ (int) $ksStore->getId() ?> %>" class="input-text<?php if ($ksStore->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID):?> required-option required-unique<?php endif; ?>" type="text" <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()):?> disabled="disabled"<?php endif;?>/></td>
            <?php endforeach; ?>
            <td id="delete_button_container_<%- data.id %>" class="col-delete ks-col-delete">
                <input type="hidden" class="delete-flag" name="option[delete][<%- data.id %>]" value="" />
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()):?>
                    <button id="delete_button_<%- data.id %>" title="<?= $block->escapeHtml(__('Delete')) ?>" type="button"
                        class="action- scalable delete delete-option"
                        >
                        <span><?= $block->escapeHtml(__('Delete')) ?></span>
                    </button>
                <?php endif;?>
            </td>
        </tr>
    </script>
</fieldset>

<script type="text/x-magento-init">
    {
        "*": {
            "Ksolves_MultivendorMarketplace/js/productattribute/ks-option": {
                "attributesData": <?= /* @noEscape */ json_encode($ksValues, JSON_HEX_QUOT) ?>,
                "isSortable":  <?= (int)(!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) ?>,
                "isReadOnly": <?= (int)$block->getReadOnly() ?>
            }
        }
    }
</script>

