<?php

/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */
?>

<!-- Manage Attribute main page start -->
<div id="product_attribute_tabs_labels" class="ks-tabcontent ks-attribute-hide-field">
    <div id="product_attribute_tabs_labels_content" class="ui-tabs-panel ui-widget-content ui-corner-bottom" role="tabpanel" aria-expanded="true" aria-hidden="false" style="display: block;">
        
        <!-- Manage label with collapse section start -->
        <div class="ks-form-fieldset">
            <div class="fieldset-wrapper admin__collapsible-block-wrapper opened ks-fieldset-wrapper ks-form-collapsible-block" id="manage-titles-wrapper">
                
                <!-- Manage label Title start -->
                <div class="ks-fieldset-wrapper-title">
                    <strong class="ks-form-collapsible-title" data-toggle="collapse" data-target="#manage-titles-content" aria-expanded="true">
                        <span><?= $block->escapeHtml(__("Manage Titles (Size, Color, etc.)")) ?></span>
                    </strong>
                </div>
                <!-- Manage label Title end -->

                <div class="fieldset-wrapper-content in collapse show ks-fieldset-wrapper-content" id="manage-titles-content">
                    <fieldset class="admin__fieldset fieldset">
                        
                        <!--manage label table end -->
                        <div class="admin__control-table-wrapper ks-advance-table" id="ks-manage-options-panel">
                            <table class="admin__control-table ks-tiers_table" id="attribute-labels-table">
                                <thead>
                                    <?php foreach ($block->getKsStores() as $ksStore): ?>
                                        <th class="col-store-view"><?= $block->escapeHtml($ksStore->getName()) ?></th>
                                    <?php endforeach; ?>
                                </thead>
                                <tbody>
                                    <tr>
                                        <?php $ksLabels = $block->getKsLabelValues() ? $block->getKsLabelValues() : $block->getKsLabelValuesError() ?>
                                        <?php foreach ($block->getKsStores() as $ksStore): ?>
                                            <td class="col-store-view">
                                                <?php $isKsRequired = $ksStore->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID; ?>
                                                <?php $isKsRequiredClass = $isKsRequired ? 'required-option' : ''; ?>
                                                <input class="input-text validate-no-html-tags <?= /* @noEscape */ $isKsRequiredClass ?>" type="text" name="frontend_label[<?= $block->escapeHtmlAttr($ksStore->getId()) ?>]" 
                                                value="<?= $block->escapeHtmlAttr($ksLabels[$ksStore->getId()]) ?>"
                                                <?php if ($block->getReadOnly()): ?>
                                                    disabled="disabled"
                                                    <?php endif;?>/>
                                            </td>
                                        <?php endforeach; ?>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <!--manage label table end -->

                    </fieldset>                                            
                </div>
            </div>
        </div>    
        <!-- Manage label with collapse section end -->

    </div>
</div>
<!-- Manage Attribute main page end -->