<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

$ksStores = $block->getStoresSortedBySortOrder();
?>
<fieldset class="fieldset ks-text-swatch mt-5 ks-attribute-hide-field">
    <div class="ks-form-collapsible-block">
        <div class="ks-fieldset-wrapper-title">
            <div class="ks-form-collapsible-title ks-after-none ks-cursor-inherit">
            <span><?= $block->escapeHtml(__('Manage Swatch (Values of Your Attribute)')) ?></span>
            </div>
        </div>
    </div>
    <div class="admin__control-table-wrapper ks-advance-table" id="swatch-text-options-panel">
        <table class="data-table clearfix ks-tiers_table table" cellspacing="0">
            <thead>
                <tr id="swatch-text-options-table">
                    <th class="col-draggable ks-draggable-handle"></th>
                    <th class="col-default"><span><?= $block->escapeHtml(__('Is Default')) ?></span></th>
                    <?php foreach ($ksStores as $ksStore): ?>
                        <th class="col-swatch col-swatch-min-width col-<%- data.id %><?= ($ksStore->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) ? ' _required' : '' ?>"
                            colspan="2">
                             <?php  if ($ksStore->getName() == 'Admin'):?>
                                <span><?= $block->escapeHtml(__('Default')) ?></span>
                            <?php else:?>
                                <span><?= $block->escapeHtml(__($ksStore->getName())) ?></span>
                            <?php endif;?>
                        </th>
                    <?php endforeach; ?>
                    <?php $ksColTotal = count($ksStores) * 2 + 3; ?>
                    <th class="col-delete ks-col-delete">&nbsp;</th>
                </tr>
            </thead>
            <tbody data-role="swatch-text-options-container" class="ignore-validate"></tbody>
            <tfoot>
                <tr>
                    <th colspan="<?= (int)$ksColTotal ?>" class="col-actions-add ks-col-actions-add">

                        <button id="add_new_swatch_text_option_button"
                        title="<?= $block->escapeHtml(__('Add Swatch')) ?>"
                        type="button" class="action- scalable add primary">
                        <span><?= $block->escapeHtml(__('Add Swatch')) ?></span>
                        </button>
                    </th>
                </tr>
            </tfoot>
        </table>
    <input type="hidden" id="swatch-text-option-count-check" value="" />
</div>
<script id="swatch-text-row-template" type="text/x-magento-template">
    <tr>
        <td class="col-draggable ks-draggable-handle">

            <div data-role="draggable-handle"
            class="draggable-handle"
            title="<?= $block->escapeHtmlAttr(__('Sort Option')) ?>"></div>

            <input data-role="order" type="hidden" name="optiontext[order][<%- data.id %>]"
            value="<%- data.sort_order %>"
            />
        </td>
        <td class="col-default">
            <input class="input-radio"
            type="<%- data.intype %>"
            name="defaulttext[]"
            value="<%- data.id %>" <%- data.checked %>/>
        </td>
        <?php foreach ($ksStores as $ksStore): ?>
            <?php $ksStoreId = (int)$ksStore->getId(); ?>
            <td class="col-swatch col-swatch-min-width col-<%- data.id %>">
                <input class="input-text
                swatch-text-field-<?= /* @noEscape */ $ksStoreId ?>
                <?= ($ksStoreId == \Magento\Store\Model\Store::DEFAULT_STORE_ID) ? ' required-option required-unique' : '' ?>"
                name="swatchtext[value][<%- data.id %>][<?= /* @noEscape */ $ksStoreId ?>]"
                type="text" value="<%- data.swatch<?= /* @noEscape */ $ksStoreId ?> %>"
                placeholder="<?= $block->escapeHtmlAttr(__("Swatch")) ?>"/>
            </td>
            <td class="col-swatch-min-width swatch-col-<%- data.id %>">
                <input name="optiontext[value][<%- data.id %>][<?= /* @noEscape */ $ksStoreId ?>]"
                value="<%- data.store<?= /* @noEscape */ $ksStoreId ?> %>"
                class="input-text<?= ($ksStoreId == \Magento\Store\Model\Store::DEFAULT_STORE_ID) ? ' required-option' : '' ?>"
                type="text" 
                placeholder="<?= $block->escapeHtmlAttr(__("Description")) ?>"/>
            </td>
        <?php endforeach; ?>
        <td id="delete_button_swatch_container_<%- data.id %>" class="col-delete ks-col-delete">
            <input type="hidden" class="delete-flag" name="optiontext[delete][<%- data.id %>]" value="" />

            <button title="<?= $block->escapeHtmlAttr(__('Delete')) ?>" type="button"
                class="action- scalable delete delete-option">
                <span><?= $block->escapeHtml(__('Delete')) ?></span>
            </button>

        </td>
    </tr>
</script>
<script type="text/x-magento-init">
{ "*": {
        "Ksolves_MultivendorMarketplace/js/productattribute/ks-text-swatch": <?= /* @noEscape */ $block->getJsonConfig() ?> 
        }
}
</script>
</fieldset>
