<?php
/**
 * Ksolves
 *
 * @category  Ksolves
 * @package   Ksolves_MultivendorMarketplace
 * @author    Ksolves Team
 * @copyright Copyright (c) Ksolves India Limited (https://www.ksolves.com/)
 * @license   https://store.ksolves.com/magento-license
 */

$ksStores = $block->getStoresSortedBySortOrder();

?>
<fieldset class="admin__fieldset fieldset ks-visual-swatch mt-5 ks-attribute-hide-field">
    <div class="ks-form-collapsible-block">
        <div class="ks-fieldset-wrapper-title">
            <div class="ks-form-collapsible-title ks-after-none ks-cursor-inherit">
            <span><?= $block->escapeHtml(__('Manage Swatch (Values of Your Attribute)')) ?></span>
            </div>
        </div>
    </div>
    <div class="admin__control-table-wrapper ks-advance-table" id="swatch-visual-options-panel">
        <table class="data-table clearfix ks-tiers_table table" cellspacing="0">
            <thead>
            <tr id="swatch-visual-options-table">
                <th class="col-draggable ks-draggable-handle"></th>
                <th class="col-default"><span><?= $block->escapeHtml(__('Is Default')) ?></span></th>
                <th><span><?= $block->escapeHtml(__('Swatch')) ?></span></th>
                <?php foreach ($ksStores as $ksStore): ?>
                    <th<?= ($ksStore->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) ? ' class="_required"' : '' ?>>
                        <?php  if ($ksStore->getName() == 'Admin'):?>
                            <span><?= $block->escapeHtml(__('Default')) ?></span>
                        <?php else:?>
                            <span><?= $block->escapeHtml(__($ksStore->getName())) ?></span>
                        <?php endif;?>
                    </th>
                <?php endforeach; ?>
                <?php $ksColTotal = count($ksStores) * 2 + 3; ?>
                <th class="col-delete ks-col-delete">&nbsp;</th>
            </tr>
            </thead>
            <tbody data-role="swatch-visual-options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="<?= (int)$ksColTotal ?>" class="col-actions-add ks-col-actions-add">
                    
                        <button id="add_new_swatch_visual_option_button"
                                title="<?= $block->escapeHtml(__('Add Swatch')) ?>"
                                type="button" class="action- scalable add primary">
                            <span><?= $block->escapeHtml(__('Add Swatch')) ?></span>
                        </button>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="swatch-visual-option-count-check" value="" />
    </div>
    <script id="swatch-visual-row-template" type="text/x-magento-template">
        <tr>
            <td class="col-draggable ks-draggable-handle">
                
                    <div data-role="draggable-handle" class="draggable-handle"
                         title="<?= $block->escapeHtml(__('Sort Option')) ?>"></div>
                
                <input data-role="order" type="hidden" name="optionvisual[order][<%- data.id %>]"  value="<%- data.sort_order %>" />
            </td>
            <td class="col-default align-middle">
                <input class="input-radio" type="<%- data.intype %>" name="defaultvisual[]" value="<%- data.id %>" <%- data.checked %>/>
            </td>
            <td class="swatches-visual-col col-default <%- data.empty_class %>">
                <input id="swatch_visual_value_<%- data.id %>" type="hidden" name="swatchvisual[value][<%- data.id %>]" value="<%- data.defaultswatch0 %>" />
                <div class="swatch_window" id="swatch_window_option_<%- data.id %>" style="<%- data.swatch0 %>"></div>
                <div class="swatch_sub-menu_container" id="swatch_container_option_<%- data.id %>">
                    <div class="swatch_row position-relative">
                        <div class="swatch_row_name colorpicker_handler">
                            <p><?= $block->escapeHtml(__('Choose a color')) ?></p>
                        </div>
                    </div>
                    <div class="swatch_row">
                        <div class="swatch_row_name btn_choose_file_upload" id="swatch_choose_file_option_<%- data.id %>">
                            <p><?= $block->escapeHtml(__('Upload a file')) ?></p>
                        </div>
                    </div>
                    <div class="swatch_row">
                        <div class="swatch_row_name btn_remove_swatch">
                            <p><?= $block->escapeHtml(__('Clear')) ?></p>
                        </div>
                    </div>
                </div>
            </td>
            <?php foreach ($ksStores as $ksStore): ?>
                <td class="swatch-col-<%- data.id %>">
                    <input name="optionvisual[value][<%- data.id %>][<?= (int)$ksStore->getId() ?>]"
                           value="<%- data.store<?= (int) $ksStore->getId() ?> %>"
                           class="input-text<?= ($ksStore->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID) ? ' required-option required-unique' : '' ?>"
                           type="text" />
                </td>
            <?php endforeach; ?>
            <td id="delete_button_swatch_container_<%- data.id %>" class="col-delete ks-col-delete"">
                <input type="hidden" class="delete-flag" name="optionvisual[delete][<%- data.id %>]" value="" />
                    <button title="<?= $block->escapeHtml(__('Delete')) ?>" type="button"
                            class="action- scalable delete delete-option">
                        <span><?= $block->escapeHtml(__('Delete')) ?></span>
                    </button>
            </td>
        </tr>
    </script>
    <?php 
        // Decode Json File fro adding Form Key in the Data
      $ksValue = json_decode($block->getJsonConfig());
      // Convert object in array
      $ksValue = (array)$ksValue;
      // Add Form key in the data
      $ksValue['form_key'] = $block->getFormKey();
      // Encode the Data in JSON Format
      $ksValue = json_encode($ksValue);
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Ksolves_MultivendorMarketplace/js/productattribute/ks-visual-swatch": <?= /* @noEscape */ $ksValue ?>
                }
        }
    </script>
</fieldset>
